### PR TITLE
Fix for product dashboard commits move and hygieia publisher plugin change to accommodate artifact extension

### PR DESCRIPTION
**Pull request by nireeshT**
Fix for product dashboard commits move and hygieia publisher plugin change to accommodate artifact extension

### CODE REVIEW

**Comment by MarkRx** [comment]
@nireeshT could you also apply the change from https://github.com/capitalone/Hygieia/issues/1254#issuecomment-288962401 to DynamicPipelineServiceImpl.java while you are in there? Thanks.

**Comment by nireeshT** [comment]
@MarkRx  - Done

**Comment by rob-miller-777** [comment]
Seems to be working as I would expect now.  The one thing I still haven't figured out is how to get a "prod" stage.  But I will keep poking around and see if I can figure that out.

**Comment by rob-miller-777** [comment]
I found it, didn't realize you needed to click that radio button on the pipeline widget.  Probably need to add a label to that or something.

**Comment by nireeshT** [comment]
resolves - https://github.com/capitalone/Hygieia/issues/1248 
https://github.com/capitalone/Hygieia/issues/1254
https://github.com/capitalone/Hygieia/issues/1165
https://github.com/capitalone/Hygieia/issues/604

**Comment by rob-miller-777** [comment]
haha, I guess it is clearly called out in the config for that widget.  Guess that's what I get for not reading...

**Comment by tabladrum** [comment]
LOL.

**Pull request merged**
