### PR TITLE
Fix for 984 and 967

### PR DESCRIPTION
**Pull request by nireeshT**
Fix for #984

### CODE REVIEW

**Comment by nireeshT** [comment]
Fix for https://github.com/capitalone/Hygieia/issues/984
    & 
Fix for https://github.com/capitalone/Hygieia/issues/967

**Comment by satishc1** [comment]
LGTM

**Comment by nireeshT** [comment]
Fix for https://github.com/capitalone/Hygieia/issues/586, https://github.com/capitalone/Hygieia/issues/735,
https://github.com/capitalone/Hygieia/issues/349

**Comment by mrpudn** [comment]
Can you rebase this one @nireeshT?

**Pull request merged**
