### PR TITLE
fix for Null when loading dashboard

### PR DESCRIPTION
**Pull request by nitin1706**
fix for #1317

### CODE REVIEW

**Comment by nitin1706** [comment]
@nireeshT

**Comment by nireeshT** [comment]
@nitin1706  - what is the use case? can you reproduce this issue ?

**Comment by nitin1706** [comment]
fix for issue #1317, 
Case 1: Re-produced this issue(#1317) by deleting components and then try fetching dashboards. 
Case 2: For delete scenarios, in case, it need to delete component first and then delete dashboard. Use Case: in case, components are not deleted, it will fail with error message that dashboard cannot be deleted, while dashboard actually would have been deleted.

**Comment by satishc1** [comment]
Closed.

**Pull request closed without merging**
