### PR TITLE
Fixing lexically nested statement in isInArray

### PR DESCRIPTION
**Pull request by desertblade**
For issue #773 

-Removed duplicate nested function isInArray
-Added a few missing semicolons (Jslint found)

Tested in Chrome and Safari.

### CODE REVIEW

**Comment by tabladrum** [comment]
@desertblade Did you submit the CLA? Thanks for the PR.

**Comment by tabladrum** [comment]
LGTM

**Comment by amitmawkin** [comment]
LGTM

**Comment by amitmawkin** [comment]
@desertblade please rebase your code

**Comment by desertblade** [comment]
Waiting on approval for the CLA.  Will rebase as soon as it is done.

**Comment by desertblade** [comment]
Signed CLA  and rebased. Should be good to pull in.

**Pull request merged**
