### PR TITLE
Reduce coupling between artifacts and builds collections

### PR DESCRIPTION
**Pull request by MarkRx**
Implementation of #806

Changes data model of artifacts from:
```
{
    "_id" : ObjectId("57d2c61646e0fb000d3ef42d"),
    "_class" : "com.capitalone.dashboard.model.BinaryArtifact",
    "timestamp" : NumberLong(0),
    "artifactName" : "Helloworld",
    "canonicalName" : "Helloworld",
    "artifactGroupId" : "mygroup",
    "artifactVersion" : "myversion",
    "buildInfo" : {
        "_id" : ObjectId("57d2c6014cedfd0018e051e9"),
        "collectorItemId" : ObjectId("57d15681d601800018b4e626"),
        ...
   }
}
```

to:
```
{
    "_id" : ObjectId("57d84b0346e0fb000ec42a71"),
    "_class" : "com.capitalone.dashboard.model.BinaryArtifact",
    "timestamp" : NumberLong(1473792771284),
    "artifactName" : "Helloworld",
    "canonicalName" : "Helloworld",
    "artifactGroupId" : "mygroup",
    "artifactVersion" : "myversion",
    "metadata" : {
        "jobName" : "myjob",
        "buildUrl" : "http://mybuild:8080/job/myjob/209/",
        "jobUrl" : "http://mybuild:8080/job/myjob/",
        "buildNumber" : "209",
        "instanceUrl" : "http://mybuild:8080/"
    }
}
```

- Modified /artifacts rest API endpoint slightly to accept a map of metadata
- Code that makes use of artifacts was updated to grab build information as needed by correlating jobUrl, instanceUrl, and buildNumber
- Jenkins plugin updated to work with api changes

This change allows for an independent artifact collector to be created. It also allows artifacts data to be inserted into the database before build data has been collected. Example curl to perform:

```
curl -X POST http://myapiendpoint:8080/api/artifact -H 'Content-Type: application/json' --data \
"{ \"artifactName\": \"Helloworld\", \"canonicalName\": \"Helloworld\", \"artifactGroup\": \"mygroup\", \"artifactVersion\": \"$projectVersion\", \"timestamp\": $(date +%s%3N), \"metadata\": { \"buildUrl\": \"$BUILD_URL\", \"buildNumber\" : $BUILD_NUMBER, \"jobName\": \"$JOB_NAME\", \"jobUrl\": \"$JOB_URL\", \"instanceUrl\": \"$JENKINS_URL\" } }"
```

Code added from #830:
The following metadata is now published with the jenkins plugin

scmUrl
scmBranch
scmRevisionNumber

### CODE REVIEW

**Comment by tabladrum** [comment]
I agree with the proposal in principle (i.e, decoupling). Need to review the impacts before we merge.

**Comment by MarkRx** [comment]
Note that the change does break backwards compatibility. If backwards compatibility is needed I could keep the build field on the artifacts document and fall back to it if the required build metadata cannot be found. The other option would be data migration - populating metadata based on existing Build information.

**Comment by MarkRx** [comment]
rebased

**Comment by MarkRx** [comment]
Added code from #830 for simplicity of merging

**Comment by MarkRx** [comment]
@tabladrum for load balancing urls do you think something like this might work?

Basically for url compares

1. remove trailing git
2. compare root domain and ignore subdomains (so server1.mycompany.com/myrepo and server2.mycompany.com/myrepo would match)

```
    @SuppressWarnings("PMD.NPathComplexity")
    public static boolean smartUrlEquals(String url1, String url2) {
    	String u1 = nullSafe(url1);
    	String u2 = nullSafe(url2);
    	
    	String u1Host = null;
    	String u1Path = null;
    	String u1Query = null;
    	
    	String u2Host = null;
    	String u2Path = null;
    	String u2Query = null;
    	try {
    		if (u1.length() > 0) {
    			URL url = new URL(u1);
    			u1Host = url.getHost();
    			u1Path = url.getPath();
    			u1Query = url.getQuery();
    		}
    	} catch (MalformedURLException e) {
    		LOGGER.warn("Invalid Url " + e.getMessage(), e);
    	}
    	u1Host = nullSafe(u1Host);
    	u1Path = nullSafe(u1Path);
    	u1Query = nullSafe(u1Query);
    	
    	try {
    		if (u2.length() > 0) {
    			URL url = new URL(u2);
    			u2Host = url.getHost();
    			u2Path = url.getPath();
    			u2Query = url.getQuery();
    		}
    	} catch (MalformedURLException e) {
    		LOGGER.warn("Invalid Url " + e.getMessage(), e);
    	}
    	
    	u2Host = nullSafe(u2Host);
    	u2Path = nullSafe(u2Path);
    	u2Query = nullSafe(u2Query);
    	
    	if (u1Path.endsWith(".git")) {
    		u1Path = u1Path.substring(0, u1Path.length() - 4);
    	}
    	
    	if (u2Path.endsWith(".git")) {
    		u2Path = u2Path.substring(0, u2Path.length() - 4);
    	}
    	
    	// TODO find a better way to handle load balancers
    	String u1PrimaryDomain = u1Host;
    	String u2PrimaryDomain = u2Host;
    	
    	int idx;
    	idx = u1Host.lastIndexOf('.');
    	if (idx > 0) {
    		idx = u1Host.lastIndexOf('.', idx - 1);
    	}
    	if (idx >= 0) {
    		u1PrimaryDomain = u1Host.substring(idx);
    	}
    	
    	idx = u2Host.lastIndexOf('.');
    	if (idx > 0) {
    		idx = u2Host.lastIndexOf('.', idx - 1);
    	}
    	if (idx >= 0) {
    		u2PrimaryDomain = u2Host.substring(idx);
    	}
    	
    	return safeEquals(u1PrimaryDomain, u2PrimaryDomain)
    			&& safeEquals(u1Path, u2Path)
    			&& safeEquals(u1Query, u2Query);
    }
    
    private static String nullSafe(String str) {
    	return str == null? "" : str;
    }
    
    private static boolean safeEquals(Object o1, Object o2) {
        if (o1 == o2) {
            return true;
        }
        if (o1 == null || o2 == null) {
            return false;
        }
        return o1.equals(o2);
    }
```

**Comment by MarkRx** [comment]
rebased

**Comment by MarkRx** [comment]
@tabladrum If I make a change to keep backwards compatability while still having the ability to store metadata on the artifacts would it make it easier to get this PR accepted?

**Comment by tabladrum** [comment]
Let's make it backward compatible. That's the best way for now. Thanks!!!

**Comment by MarkRx** [comment]
@tabladrum done

**Comment by tabladrum** [comment]
@MarkRx will review this weekend. Thanks again!

**Comment by MarkRx** [comment]
rebased

**Comment by tabladrum** [comment]
LGTM

**Comment by satishc1** [comment]
LGTM

**Pull request merged**
