### PR TITLE
Moved collectors into their own directory

### LINKED ISSUE #763: Collector organization
Hey @tabladrum @amitmawkin, I've noticed that the list of collectors keeps growing. Would you guys like to organize them like the following?
```
/UI
/api
/core
/collectors
  /aws-cloud-collector
  /bitbucket-scm-collector
  /jenkins-build-collector
  /jenkins-cucumber-test-collector
  /jira-feature-collector
  /sonar-codequality-collector
  /subversion-scm-collector
  /udeploy-deployment-collector
  /versionone-feature-collector
  /xldeploy-deployment-collector
  ...
...
```

I've done this with another project, and it keeps these kinds of things pretty well organized and tucked away.

Granted, it's a bit of a disruptive change, as it moves a lot of stuff.

### PR DESCRIPTION
**Pull request by mrpudn**
Resolves #763 

I moved all of the collectors into a `/collectors` directory. There were a few collectors missing from the `pom.xml` build profiles, so I added those as well. I also added a `README.md` in the collectors directory with a list of collectors that are currently in the project.

### CODE REVIEW

**Comment by amitmawkin** [comment]
LGTM @mrpudn @tabladrum @satishc1 i also did a build check, everything looks good

**Comment by tabladrum** [comment]
LGTM

**Comment by amitmawkin** [comment]
@mrpudn Zach please rebase and resolve conflicts, we had some previous PR that needs to be merged before we can accept this PR

**Comment by mrpudn** [comment]
Ok, everything should now be rebased with master

**Pull request merged**
