### PR TITLE
Add basic auth support to sonarqube collector

### PR DESCRIPTION
**Pull request by subesokun**
This PR adds HTTP basic authentication support to the SonarQube collector.

### CODE REVIEW

**Comment by subesokun** [comment]
Fixes #482

**Comment by tabladrum** [comment]
@subesokun Did you fill out the CLA? https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform

**Comment by subesokun** [comment]
@tabladrum I've submitted now the CLA.

**Comment by tabladrum** [comment]
Thanks! Will merge it is a couple of days.

**Comment by tEmEd** [comment]
Any progress on the issue?

**Pull request merged**
