### PR TITLE
Jira and Feature Widget Improvements

### PR DESCRIPTION
**Pull request by MarkRx**
Contains a number of jira and feature collector / widget changes rolled up into a single PR from @pxk5958 

Changes:

- Jira collector now supports gathering team data. In the past Jira projects were being placed into 'scope' and 'ScopeOwner' (in collector_items). Now if the tempo team field is configured in the collector the team data is placed in 'ScopeOwner'. 
- Feature widget can filter based on project name, team name, or both. To grab all items for a given field / team the 'Any' option can be selected in the drop down.
- Feature widget can be configured to list Epics (previously called 'features') or Issues (stories, defects, spikes, etc).
- Added hyperlinks to epics / issues in progress
- Added hyperlink to sprint in progress
- Issues that have been completed now have a strikethrough on the UI
- Issues are sorted by modified date. Epics are still sorted by points. We feel that when listing stories a user will be more interested in recent activity.
- Feature widget modified to display open / in progress / done estimate metrics instead of total / in progress / done as this seems to be more intuitive.
- Added the ability to collect data on multiple issues types in the Jira collector
- Improved documentation / configuration of jira collector - renamed 'feature.jiraIssueTypeId' to 'feature.jiraIssueTypeNames'

Note: the feature collection will have to be wiped / reset in order to take advantage of urls and teams

The jira collector items that correspond to scopeowners will have to be wiped as they currently store project information

@tabladrum @amitmawkin we need to know how to construct urls to versionone assets in order to have hyperlinks be available for the version one feature.

feature1

feature2

### CODE REVIEW

**Comment by MarkRx** [comment]
I recommend someone doing a quick sanity test with versionone with this branch to verify these changes did not break it. They shouldn't as they are view changes that work off the underlying data model but we don't have any way here to verify that.

**Comment by tabladrum** [comment]
@MarkRx versionone testing looks good so far. Testing more. One thing is would be nice to have: (1) Filter in selectable Teams based on project selected and (2) Filter in selectable project based on Team selected. 

Question: Do you see a project tree path based on org hierarchy in JIRA? Something like this: Company->Line of Business -> Product -> Team etc?

**Comment by tabladrum** [comment]
LGTM

**Comment by satishc1** [comment]
LGTM

**Comment by xpdable** [comment]
What's the team means in Jira ? 

> 2016-12-11 11:30:00,714 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: http://jira.bjz.apac.ime.reuters.com/rest/tempo-teams/1/team
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_91]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_91]
        at java.net.URLConnection.getContent(Unknown Source) ~[na:1.8.0_91]
        at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:192) ~[jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:61) [jira-feature-collector.jar!/:2.0.4-S
NAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEA
SE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELE
ASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_91]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
2016-12-11 11:30:08,607 DEBUG c.c.d.client.team.TeamDataClientImpl - Size of paged Jira response: 1792
2016-12-11 11:30:19,322 INFO  c.c.d.collector.CollectorTask - Team Data            1792       19s
2016-12-11 11:30:19,325 DEBUG c.c.d.c.p.ProjectDataClientImpl - Constructing data collection for the feature widget, project-level data...
2016-12-11 11:30:26,318 DEBUG c.c.d.c.p.ProjectDataClientImpl - Size of paged Jira response: 1792
2016-12-11 11:30:28,222 INFO  c.c.d.collector.CollectorTask - Project Data         1792        8s
2016-12-11 11:30:28,227 DEBUG c.c.d.c.story.StoryDataClientImpl - Constructing data collection for the feature widget, story-level data...

**Comment by pxk5958** [comment]
@xpdable Your teams need to be configured using Tempo-team plugin in JIRA. Also, please read collectors/feature/jira/README.md :

```
#############################################################################
# In Jira, your instance will have its own custom field created for "team"
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=customfield_10703
```

**Comment by xpdable** [comment]
@pxk5958 Hi, we do not use this plugin. Could I somehow disable your feature on this Team plugin in collector?

**Comment by MarkRx** [comment]
@tabladrum the project to team relationship is many to many and is not hierarchical. Teams may have work from multiple projects. Projects may have work from multiple teams.

**Comment by Gurugit1** [comment]
Not getting drop down option for project name and team name under Feature widget. I can see the projects but not getting anything under Team and as there is no drop down its not letting me save the widget. Error "select a valid team name".

How can I tackle this ?
screen shot 2017-06-02 at 11 26 04 am

**Comment by nireeshT** [comment]
@Gurugit1  - did you try giving your team name (or any team name)  in input field, it should start suggesting the values. If not check in your Mongo if team collection is populated.

**Comment by Gurugit1** [comment]
@nireeshT - I could see data in feature collection but team collection is empty.
I'm using the following properties. 

feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10002
feature.jiraStoryPointsFieldName=customfield_10003
feature.jiraTeamFieldName=

Do I need any other property ?

**Pull request merged**
