### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by depwaswho94**
Fix issue with "no need to execute it with superuser permissions"

### CODE REVIEW

**Comment by SanthiSridharan** [comment]
Hi depwaswho94 , 
We will not be able to merge this request until you sign an individual contributor License Agreement. Kindly sign the same in this link. 
https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform

**Comment by depwaswho94** [comment]
Hi, can you give me a link where i can sign the individual contributor
license agreement ?

**Comment by depwaswho94** [comment]
Hi @SanthiSridharan i am done with the CLA.

**Comment by matthewbeasley** [comment]
@depwaswho94 @satishc1 - according to the [docs](https://bower.io/docs/api/#allow-root) there's no need to run bower as superuser since it is a user command. If running `bower install` gives you a permissions error then you are likely not the owner of the folder. Run `chown -R $USER:$USER Hygieia` or something similar to make yourself owner of the folder.

**Pull request closed without merging**
