### PR TITLE
Collector config server

### PR DESCRIPTION
**Pull request by Mpluya**
As we rollout Hygieia throughout our organization, we find ourselves having to update property files to account for Jenkins or Sonar servers to pull data from, and restart corresponding applications. 

This enhancement enables maintaining this list of servers in a git repository (external from the application) and have Hygieia always pull the latest list of servers in every run without having to do any restart.

I do know there are other collectors that could take advantage of the collector-config-server. I first want to see if there's interest in this enhancement. If so, I could either apply it to the other collectors or have the community consume the collector-config-server as needed. I'm cool with either approach.

### CODE REVIEW

**Comment by tabladrum** [comment]
@Mpluya the build is failing because of Travis CI build log limitation. The fix is coming with https://github.com/capitalone/Hygieia/pull/1137

**Comment by Mpluya** [comment]
@tabladrum thanks :)

**Comment by tabladrum** [comment]
@Mpluya can you rebase? The 1137 has been merged.

**Comment by Mpluya** [comment]
@tabladrum rebase done. Thanks for the fix on limited build log.

**Comment by Mpluya** [comment]
I am closing this pull request, given the discussion in #1409. The changes in here will be leveraged for the new pull request that @rob-miller-777 and @brennanananan are working on to move the mongo related properties to the cloudConfigServer.

**Comment by Mpluya** [comment]
I am closing this pull request, given the discussion in #1409. The changes in here will be leveraged for the new pull request that @rob-miller-777 and @brennanananan are working on to move the mongo related properties to the cloudConfigServer.

**Pull request closed without merging**
