### PR TITLE
Changes for deletion confirmation dialog box.

### PR DESCRIPTION
**Pull request by NeetiM**
Changes done for delete dashboard confirmation

### CODE REVIEW

**Comment by nireeshT** [comment]
@NeetiM  - can you throw in some screenshots

**Comment by nireeshT** [comment]
@NeetiM  - We may want confirmation alert here instead of a modal popup to ask for delete. You can use swal(SweetAlert.js) to set alerts. I would create a custom directive to show confirmation alert and use it across application on delete button element (or any element which would require confirmation alert).

**Comment by NeetiM** [comment]
image

**Comment by NeetiM** [comment]
image
image
image

**Pull request closed without merging**
