### PR TITLE
UI tests

### LINKED ISSUE #1097: UI Tests
Hey everyone!

Here at my organization we have been developing some BDD tests (Selenium, Serenity for reporting) for the UI. I was wondering if there was any interest out there for the UI test suite to be contributed back.

Thanks!
Gabe

### PR DESCRIPTION
**Pull request by GabrielFabian**
resolves #1097 

Provided is an automated UI test suite using Serenity and jBehave. 

The solution has been dockerized for ease of injecting data and ensuring proper setup and tear down. (credit to @brennanananan)

* Tests can be run either locally or as a continuous integration step. (See readme for setup instructions).
* Test reports can be found in ${UI-tests}/target/site/serenity/index.html after the test suite has finished executing.
* Test data can be pre-inserted to the mongodb through the mongo_setup.js
* You may select your target webdriver based on the Selenium node image you choose.
* You are able to run tests on a UI deployed on an SSL server.

A note on completeness:
* This is merely a foundation for building a more robust UI test suite. It is out of the scope of this pull request to include tests for every feature of this product.
* As more features are developed, it will be easy for the contributor to add automated UI tests.

### CODE REVIEW

**Comment by doraemon0011** [comment]
@GabrielFabian I am trying to build UI-tests and did mvn clean install on project UI-tests. I got the below error. Please help

Console log:

BeforeStories)

Running story stories/create_dashboard_test.story

(stories/create_dashboard_test.story)
Meta:
@dashboard 
@smoke 

Using timeout for story create_dashboard_test.story of 300 secs.
Scenario: User creates a new dashboard
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1492637726564	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1492637726565	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/deployment-checker@mozilla.org.xpi
1492637726565	addons.xpi	DEBUG	Calling bootstrap method startup on deployment-checker@mozilla.org version 1.0
1492637726566	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1492637726567	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.9
1492637726567	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1492637726568	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1492637726569	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1492637726570	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1492637726573	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1492637726573	addons.manager	DEBUG	Provider finished startup: XPIProvider
1492637726574	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1492637726574	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1492637726574	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1492637726574	addons.manager	DEBUG	Starting provider: GMPProvider
1492637726586	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1492637726586	addons.manager	DEBUG	Provider finished startup: GMPProvider
1492637726586	addons.manager	DEBUG	Starting provider: PluginProvider
1492637726586	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1492637726586	addons.manager	DEBUG	Provider finished startup: PluginProvider
1492637726587	addons.manager	DEBUG	Completed startup sequence
1492637728803	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1492637728803	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1492637728804	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1492637729131	DeferredSave.extensions.json	DEBUG	Write succeeded
1492637729131	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1492637729131	DeferredSave.extensions.json	DEBUG	Starting timer
1492637729157	DeferredSave.extensions.json	DEBUG	Starting write
1492637729159	addons.repository	DEBUG	No addons.json found.
1492637729160	DeferredSave.addons.json	DEBUG	Save changes
1492637729163	DeferredSave.addons.json	DEBUG	Starting timer
1492637731730	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1492637731731	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1492637731731	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1492637731734	DeferredSave.addons.json	DEBUG	Starting write
1492637731813	DeferredSave.extensions.json	DEBUG	Write succeeded
1492637733118	DeferredSave.addons.json	DEBUG	Write succeeded
2017-04-19 17:35:40.547 plugin-container[1096:38800] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8a57, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-19 17:35:40.548 plugin-container[1096:38800] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x4b17, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-04-19 17:35:40.548 plugin-container[1096:38800] Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
JavaScript warning: http://localhost:3000/components/widgets/cloud/view.js, line 158: unreachable code after return statement

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:128)
	at net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider.newFirefoxDriver(FirefoxDriverProvider.java:67)
	at net.serenitybdd.core.webdriver.driverproviders.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:51)
	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:126)
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:144)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:135)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:105)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:180)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:175)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:829)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:739)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:727)
	at com.capitalone.dashboard.uitest.steps.UserSteps.navigate_to_login_page(UserSteps.java:23)
	at com.capitalone.dashboard.uitest.steps.UserSteps$$EnhancerByCGLIB$$a3f520d.CGLIB$navigate_to_login_page$0(<generated>)
	at com.capitalone.dashboard.uitest.steps.UserSteps$$EnhancerByCGLIB$$a3f520d$$FastClassByCGLIB$$1a679609.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:372)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:357)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:332)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at com.capitalone.dashboard.uitest.steps.UserSteps$$EnhancerByCGLIB$$a3f520d.navigate_to_login_page(<generated>)
	at com.capitalone.dashboard.uitest.definitions.CommonDefinitions.authorizeStakeholder(CommonDefinitions.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1088)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:953)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:992)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:902)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:825)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:798)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:422)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:393)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Given I am an authorized project stakeholder (FAILED)
(net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver)
And I am on the Hygieia home screen (NOT PERFORMED)
When I define a new team dashboard named 'DummyDashboard' (NOT PERFORMED)
And I create the dashboard (NOT PERFORMED)
Then the current dashboard header should read 'DummyDashboard' (NOT PERFORMED)

net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:148)
	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:135)
	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:105)
	at net.thucydides.core.webdriver.WebDriverFacade.openIgnoringHtmlUnitScriptErrors(WebDriverFacade.java:180)
	at net.thucydides.core.webdriver.WebDriverFacade.get(WebDriverFacade.java:175)
	at net.serenitybdd.core.pages.PageObject.openPageAtUrl(PageObject.java:829)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:739)
	at net.serenitybdd.core.pages.PageObject.open(PageObject.java:727)
	at com.capitalone.dashboard.uitest.steps.UserSteps.navigate_to_login_page(UserSteps.java:23)
	at com.capitalone.dashboard.uitest.steps.UserSteps$$EnhancerByCGLIB$$a3f520d.CGLIB$navigate_to_login_page$0(<generated>)
	at com.capitalone.dashboard.uitest.steps.UserSteps$$EnhancerByCGLIB$$a3f520d$$FastClassByCGLIB$$1a679609.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:372)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:357)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:332)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at com.capitalone.dashboard.uitest.steps.UserSteps$$EnhancerByCGLIB$$a3f520d.navigate_to_login_page(<generated>)
	at com.capitalone.dashboard.uitest.definitions.CommonDefinitions.authorizeStakeholder(CommonDefinitions.java:33)
	(reflection-invoke)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)
...

**Comment by GabrielFabian** [comment]
@doraemon0011 thanks for bringing that to my attention, a fix will be available soon. :rocket:

**Comment by brennanananan** [comment]
@doraemon0011 Please try again.

Some profiles were added to run the tests properly depending on your OS, see the updated README for information on those.

**Comment by doraemon0011** [comment]
@brennanananan Thanks, I changed my Mozilla firefox browser version from 52 to 30. Now the UI-Tests run succesfully with the command : mvn clean install -DUITEST_EXISTING_USERNAME=hygieia_test_user -DUITEST_EXISTING_PASSWORD=password.

 As im not using docker, is there any option to cleanup the test data from mongodb once the test run is completed

**Comment by brennanananan** [comment]
@doraemon0011 Currently there is no way to easily clean up the database inside the UI test execution. The reason we preferred to use the docker solution was so that we could perform whatever operations on the database that we needed, and then simply stop the container at the end. In that scenario, cleanup is not needed as the data is never persisted outside of the container.

**Comment by kumarvarun1252** [comment]
@GabrielFabian I am seeing the following error when I try to build the project.

```[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (docker) on project ui-tests: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]```

If I comment the docker-maven-plugin spotify in UI-tests/pom.xml, project builds without any issues.

**Comment by kumarvarun1252** [comment]
Build is successful if I set the skipDockerBuild config to true for com.spotify docker-maven-plugin. `<skipDockerBuild>true</skipDockerBuild>`

```[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.668 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 29.508 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 19.147 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SUCCESS [  3.419 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SUCCESS [  3.171 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  3.514 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  3.454 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  3.605 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SUCCESS [  1.257 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  3.249 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SUCCESS [  3.337 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [  6.774 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  3.156 s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SUCCESS [  4.787 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  0.794 s]
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SUCCESS [  2.922 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SUCCESS [  3.219 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  3.213 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  0.922 s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SUCCESS [  3.517 s]
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SUCCESS [  2.851 s]
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SUCCESS [  3.074 s]
[INFO] Hygieia Publisher Plugin ........................... SUCCESS [ 20.849 s]
[INFO] com.capitalone.dashboard:UI ........................ SUCCESS [ 21.028 s]
[INFO] com.capitalone.dashboard:ui-tests .................. SUCCESS [  1.367 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:34 min
[INFO] Finished at: 2017-07-25T14:08:57-07:00
[INFO] Final Memory: 186M/1572M
[INFO] ------------------------------------------------------------------------```

I am able to run tests with the following command
`mvn clean verify -f ./docker-pom.xml -DUITEST_EXISTING_USERNAME=hygieia_test_user -DUITEST_EXISTING_PASSWORD=password`

Tests will fail because of some changes to the UI. I have the fixes locally which I can submit once this PR is merged to master.

**Comment by satishc1** [comment]
@tabladrum LGTM

**Pull request merged**
