### PR TITLE
Nexus IQ scan enhancements - Java changes

### PR DESCRIPTION
**Pull request by Booma-Baskaran**

### CODE REVIEW

**Comment by Booma-Baskaran** [comment]
nexusiq-capture

This PR has the dependency with PR-#2192.

**Comment by tabladrum** [comment]
wow! nice!

**Comment by nireeshT** [comment]
@Booma-Baskaran  please update branch

**Comment by Booma-Baskaran** [comment]
@nireeshT - Have updated it. Please merge.

**Comment by nireeshT** [comment]
@Booma-Baskaran  working on it

**Comment by Booma-Baskaran** [comment]
Removed commented lines. Only Hygieia comments are there in the file.

**Comment by Booma-Baskaran** [comment]
@nireeshT - Any review comments are there?

**Comment by Booma-Baskaran** [comment]
@nireeshT - Can you please merge it?

**Pull request closed without merging**
