### PR TITLE
Fixed log file path for all collectors

### LINKED ISSUE #988: Collectors' logs path incorrect
Hygieia api's log gets stored in ./logs directory whereas the collectors' logs are created in the current directory itself. This inconsistency of log paths is present in src/main/resources/logback.xml

Api's logback.xml:
```xml
<fileNamePattern>logs/devopsdashboard-api-%d{yyyy-MM-dd}.%i.log</fileNamePattern>
```

Jira and other collectors' logback.xml:
```xml
<fileNamePattern>jiracollector-%d{yyyy-MM-dd}.%i.log</fileNamePattern>
```

### PR DESCRIPTION
**Pull request by MarkRx**
When running in docker logs were getting lost because they were not being placed in the correct location (logs) that was mounted.

@pxk5958 

Fixes #988

### CODE REVIEW

**Comment by tabladrum** [comment]
+1

**Comment by tabladrum** [comment]
@satishc1 take a look - I think you had a PR coming along this line. If this looks ok, LGTM it.

**Comment by satishc1** [comment]
LGTM

**Comment by tabladrum** [comment]
LGTM

**Comment by tabladrum** [comment]
strange that LGTM is not working!

**Comment by pxk5958** [comment]
What's the error?

**Comment by amitmawkin** [comment]
LGTM

**Comment by amitmawkin** [comment]
merging manually then, looks like lGTM server could be down . I saw the events went out

**Pull request merged**
