### PR TITLE
Dashboard name validation

### PR DESCRIPTION
**Pull request by Mpluya**
This is a follow up to https://github.com/capitalone/Hygieia/issues/1067.
Added client and server side validation on the dashboard name to only allow letter, numbers or spaces.

### CODE REVIEW

**Comment by nireeshT** [comment]
@Mpluya  - Can we have the similar change for "rename dashboard" as well under same PR.

**Comment by Mpluya** [comment]
@nireeshT good point. Will do.

**Comment by Mpluya** [comment]
@nireeshT updates pushed. Summary of changes:

- added regex validation on rename of dashboard title
- enhanced server side validation on the required fields for a dashboard by adding a size check since UI posts empty string which bypasses the not null check
- added tests on rename dashboard

**Comment by nireeshT** [comment]
@tabladrum @satishc1  - LGTM.

**Comment by tabladrum** [comment]
LGTM

**Pull request merged**
