### PR TITLE
correcting if condition on JENKINS_OP_CENTER

### PR DESCRIPTION
**Pull request by Mpluya**
Problem: The Hygieia Jenkins Collector docker container fails on startup. The docker file runs a shell script to build property file. This shell script has an incorrectly declared if condition (was using parenthesis instead of brackets).

### CODE REVIEW

**Comment by MarkRx** [comment]
@pxk5958

**Comment by tabladrum** [comment]
@pxk5958 @MarkRx for review.

**Comment by pxk5958** [comment]
Can confirm. This corrects the following error which was present before our changes:
` ./jenkins-build-properties-builder.sh: line 124: : command not found`

**Comment by tabladrum** [comment]
lgtm

**Comment by mrpudn** [comment]
LGTM - just needs rebasing

**Comment by mdskd** [comment]
@amitmawkin any chance of getting this merged in? updated branch.

**Comment by amitmawkin** [comment]
LGTM

**Comment by tabladrum** [comment]
done!

**Comment by amitmawkin** [comment]
lol , i was trying to do the same

**Comment by tabladrum** [comment]
I beat you :-)

**Comment by mdskd** [comment]
thank you gentlemen!

**Pull request merged**
