### PR TITLE
Handling multiple cross functional deployment servers

### PR DESCRIPTION
**Pull request by MarkRx**
This change allows the deployment widgets to handle more than one server. It has a configuration that can be set to allow this.

Use case: We have multiple deployment servers that are split up by function. One handles prod and prod-like environments. The other handles test, qa, and dev environments. Data gathered from multiple servers needs to be correlated together and treated as one application.

Changes:
- API now supports multiple deployment collectors per a single dashboard
- UI has ability to correlate applications together by ID (when enabled) thus allowing multiple deployment collector items to be used under the hood.
- Add API + UI configurable options ( #890 )

Changes will work with existing documents in the database.

### CODE REVIEW

**Comment by MarkRx** [comment]
rebased

**Comment by MarkRx** [comment]
Added system wide configurations ( #890 )

**Comment by tabladrum** [comment]
@MarkRx Can you include some sample screen shots?

**Comment by MarkRx** [comment]
crossdeployexampleb

In this example there is one app that exists (with the same application id) in sandbox, devdeploy, and deploy. Apps below it are in devdeploy and deploy. The app on top is only in devdeploy.

Sample database component:
```
{
    "_id" : ObjectId("582a2f3246e0fb000d2633ee"),
    "_class" : "com.capitalone.dashboard.model.Component",
    "name" : "A Name",
    "collectorItems" : {
        "Deployment" : [ 
            {
                "_id" : ObjectId("5823924fdc0e82001290afb5"),
                "description" : "bla",
                "niceName" : "XLD Devdeploy",
                "enabled" : true,
                "pushed" : false,
                "collectorId" : ObjectId("5823924cdc0e82001290ae36"),
                "lastUpdated" : NumberLong(0),
                "options" : {
                    "applicationType" : "udm.Application",
                    "applicationId" : "Applications/foo/bar",
                    "applicationName" : "A Name",
                    "instanceUrl" : "http://myurl1.com"
                }
            }, 
            {
                "_id" : ObjectId("58239253dc0e82001290b1e6"),
                "description" : "bla",
                "niceName" : "XLD Deploy",
                "enabled" : true,
                "pushed" : false,
                "collectorId" : ObjectId("5823924cdc0e82001290ae36"),
                "lastUpdated" : NumberLong(0),
                "options" : {
                    "applicationType" : "udm.Application",
                    "applicationId" : "Applications/foo/bar",
                    "applicationName" : "A Name",
                    "instanceUrl" : "http://myurl2.com"
                }
            }
        ]
    }
}
```

Everything else works the same. The component simply has more than one collector item attached (one for each server). The UI and API layer was updated to account for this.

**Comment by MarkRx** [comment]
rebased

**Comment by tabladrum** [comment]
LGTM

**Comment by satishc1** [comment]
LGTM

**Pull request merged**
