### PR TITLE
Jira and VersionOne refactoring

### PR DESCRIPTION
**Pull request by satishc1**
Jira and VersionOne refactoring in terms of making it uniform and also matching the overall design pattern of the rest of Hygieia.

1. Do not create any collector item from either VersionOne or Jira collector. Only create team and/or scope documents.
2. UI drop downs fetches data from scope (for Project drop down) and team (for team drop down)
3. Once UI config is saved, create a CollectorItem with the combination configured. The collector item will have the project and team selected on the UI. One of these has to be present, both can't be null (error validation on UI)
4. Jira collector and VersionOne collector collects feature data based on the project+team in the collector item collection. This can potentially save a lot of time in data collection too. (NOTE: This one is not included in this PR, it will be done in the future).
5. View options (such as Scrum or Kanban, Points or Count or Hours etc) are as usual saved in widget config options.

Steps to re-run the jira / versionone collectors once the PR is merged:

1. Make a backup of your database.
2. delete collector_items where collectorId in (select collectors.id from collectors where collectors.name in ("Jira", "VersionOne") )
3. delete collectors where collectorType in ("Feature", "Scope", "ScopeOwner") 
4. Drop feature , scope , team
5. Run jira and versionone collector
6. Open your dashboard and re-configure your feature widget to pick the right project / team value.

Script for Steps 2, 3 and 4 is given below.

```
db.collectors.find({
	"name" : { $in : ["Jira", "VersionOne"] }   
}).forEach(
	function(myDoc) {
		print('Dropping collector_items where collectorId is ' + myDoc._id);
		db.collector_items.remove( {"collectorId" : myDoc._id} );
	}
);

print('Dropping collectors where collectorType in Feature, Scope, ScopeOwner');
db.collectors.remove({ "collectorType" : { $in : ["Feature", "Scope", "ScopeOwner"] } });

print('Dropping feature collection');
db.feature.drop();

print('Dropping scope collection');
db.scope.drop();

print('Dropping team collection');
db.team.drop();
```

### CODE REVIEW

**Comment by satishc1** [comment]
@MarkRx @tabladrum Please take look. I have tested teams with VersionOne, but I haven't tested tempo teams with jira.

**Comment by MarkRx** [comment]
Running for me results in an exception. Something is reading in ScopeOwner somewhere and trying to convert it to that enum. You might need to add it back in even if it just sits there as a deprecated record.

> 2017-01-31 16:16:49,388 ERROR c.c.d.rest.RestApiExceptionHandler - Failed to convert from type java.lang.String to type com.capitalone.dashboard.model.CollectorType for value 'ScopeOwner'; nested exception is java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.CollectorType.ScopeOwner
> org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.lang.String to type com.capitalone.dashboard.model.CollectorType for value 'ScopeOwner'; nested exception is java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.CollectorType.ScopeOwner
>         at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:176) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readMap(MappingMongoConverter.java:948) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:217) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1185) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.access$200(MappingMongoConverter.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1133) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getValueInternal(MappingMongoConverter.java:869) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter$1.doWithPersistentProperty(MappingMongoConverter.java:282) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter$1.doWithPersistentProperty(MappingMongoConverter.java:270) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:309) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:270) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:231) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readCollectionOrArray(MappingMongoConverter.java:904) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1183) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.access$200(MappingMongoConverter.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1133) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getValueInternal(MappingMongoConverter.java:869) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.DefaultDbRefResolverCallback.resolve(DefaultDbRefResolverCallback.java:59) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.DefaultDbRefResolver.resolveDbRef(DefaultDbRefResolver.java:90) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at 
> org.springframework.data.mongodb.core.convert.MappingMongoConverter$2.doWithAssociation(MappingMongoConverter.java:304) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:339) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:287) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:231) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1185) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.access$200(MappingMongoConverter.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1133) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getValueInternal(MappingMongoConverter.java:869) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter$1.doWithPersistentProperty(MappingMongoConverter.java:282) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter$1.doWithPersistentProperty(MappingMongoConverter.java:270) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:309) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:270) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:231) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:191) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:187) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:78) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.MongoTemplate$ReadDbObjectCallback.doWith(MongoTemplate.java:2206) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1884) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1707) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1690) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:602) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:268) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:227) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.findAll(SimpleMongoRepository.java:47) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_121]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_121]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_121]
>         at 
> org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:475) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
> at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:460) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
>         at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at com.sun.proxy.$Proxy78.findAll(Unknown Source) ~[na:na]
>         at com.capitalone.dashboard.service.DashboardServiceImpl.all(DashboardServiceImpl.java:59) ~[api.jar!/:2.0.5-SNAPSHOT]
>         at com.capitalone.dashboard.rest.DashboardController.dashboards(DashboardController.java:39) ~[api.jar!/:2.0.5-SNAPSHOT]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_121]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_121]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_121]
>         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) ~[spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) [spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) [spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) [spring-webmvc-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) 

> [tomcat-embed-core-8.0.23.jar!/:8.0.23]
> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at com.capitalone.dashboard.config.LoggingFilter.doFilter(LoggingFilter.java:111) [api.jar!/:2.0.5-SNAPSHOT]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85) [spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_121]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_121]
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.23.jar!/:8.0.23]
>         at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]
> Caused by: java.lang.IllegalArgumentException: No enum constant com.capitalone.dashboard.model.CollectorType.ScopeOwner
>         at java.lang.Enum.valueOf(Unknown Source) ~[na:1.8.0_121]
>         at org.springframework.core.convert.support.StringToEnumConverterFactory$StringToEnum.convert(StringToEnumConverterFactory.java:59) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.core.convert.support.StringToEnumConverterFactory$StringToEnum.convert(StringToEnumConverterFactory.java:45) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.core.convert.support.GenericConversionService$ConverterFactoryAdapter.convert(GenericConversionService.java:425) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:35) ~[spring-core-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
>         ... 104 common frames omitted

**Comment by satishc1** [comment]
@MarkRx @tabladrum Edited cleanup steps to add this line below. Please try it out and let us know if the exception is resolved.
db.collectors.remove({   "collectorType" : { $in : ["Feature", "Scope", "ScopeOwner"] }   });

**Comment by MarkRx** [comment]
That will work, but are you prepared to handle all of the jira issues that are raised due to collectors breaking on an upgrade? Is there harm in just letting the stale records linger?

**Comment by tabladrum** [comment]
I think we are going to put those back as deprecated. And take it out at a later date. @satishc1 is updating the PR.

**Comment by satishc1** [comment]
@MarkRx @tabladrum Added the deprecated collector types and committed. Will take these out at a later date.

**Comment by MarkRx** [comment]
Will test this afternoon.

**Comment by MarkRx** [comment]
Nothing shows up under the "Agile Content Tool Type:" dropdown

**Comment by satishc1** [comment]
@MarkRx Did you do "Step 5. Run jira and versionone collector"  after cleaning up the collections ?

**Comment by satishc1** [comment]
@MarkRx Good to know its working well. Running Step 5 creates the AgileTool collectors.

**Comment by MarkRx** [comment]
Yes. I intentionally did not clean up any data because that is what the vast majority of users are going to do when upgrading. I wanted to experience what they would encounter.

**Comment by tinabear** [comment]
Jira collector is not working with our Jira instance which no Team plugin is installed on.

2017-02-02 12:00:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2017-02-02 12:00:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-02 12:00:00,008 INFO  c.c.d.collector.CollectorTask - https://jira.xxxxxxxx.com/
2017-02-02 12:00:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2017-02-02 12:00:00,008 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2017-02-02 12:00:00,312 INFO  c.c.d.collector.CollectorTask - Project Data           13        0s
2017-02-02 12:00:00,431 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.NullPointerException: null
        at com.capitalone.dashboard.util.FeatureWidgetQueries.getStoryQuery(FeatureWidgetQueries.java:111) ~[jira-feature-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.DefaultJiraClient.getIssues(DefaultJiraClient.java:94) ~[jira-feature-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:160) ~[jira-feature-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

Anything needs to be changed in the configuration file? I just make feature.jiraTeamFieldName blank.

Thank you,

Dongsheng

**Comment by rob-miller-777** [comment]
To @MarkRx 's point, I was looking through the code yesterday, and it seems like saving of the collector information doesn't work as intended.  When changes are made to properties of a collector, such as the "collectorType", they are overwritten by their previous value before being saved.  I was going to open an issue on that since I wasn't sure if that was intentional, or a bug.  

This can be seen on line 55 in this file: https://github.com/capitalone/Hygieia/blob/master/core/src/main/java/com/capitalone/dashboard/collector/CollectorTask.java

It looks like it should probably keep the "id" from the old collector, but allow the other properties to be updated.

**Comment by anandsit** [comment]
Do you want me to upgrade Hygiei API and UI as well.

After pulling the latest code, i built only Jira collector. Performed all the mentioned cleanup task. Ran the new jira collector. The entry in the database looks like this

{
    "_id" : ObjectId("589bcd2fc4c9565faf4ef41a"),
    "_class" : "com.capitalone.dashboard.model.FeatureCollector",
    "name" : "Jira",
    "collectorType" : "AgileTool",
    "enabled" : true,
    "online" : true,
    "lastExecuted" : NumberLong(1486605818627)
}

With this, UI did not recognize the collector (the drop down did not show  Jira as an option). 

When i change the collectorType from AgileTool to ScopeOwner, the dropdown is populated But the values in the UI are still 0 0 0 for any project and any value


2017-02-08 20:20:15,214 ERROR c.c.d.client.DefaultJiraClient - IOException
java.io.FileNotFoundException: https://jira.jcpenney.com/rest/tempo-teams/1/team
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_74]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_74]
        at java.net.URLConnection.getContent(Unknown Source) ~[na:1.8.0_74]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContent(Unknown Source) ~[na:1.8.0_74]
        at com.capitalone.dashboard.client.DefaultJiraClient.getTeams(DefaultJiraClient.java:196) ~[jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:57) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:107) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:2.0.5-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_74]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_74]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_74]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_74]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_74]
2017-02-08 20:20:15,214 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2017-02-08 20:20:15,967 INFO  c.c.d.collector.CollectorTask - Project Data          331        0s
2017-02-08 20:20:16,672 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 1
2017-02-08 20:20:16,673 INFO  c.c.d.collector.CollectorTask - Story Data              1        0s
2017-02-08 20:20:16,673 INFO  c.c.d.collector.CollectorTask - Finished                         1s

**Pull request merged**
