### PR TITLE
Angular/UI-Bootstrap Update to latest

### PR DESCRIPTION
**Pull request by rob-miller-777**
Updated Angular version to latest stable release of Angular (1.5.9), as well as updated version of UI-Bootstrap (2.3.0).  

Most of the changes that had to be made outside of the version changes revolved around Angular Bootstrap, and Angular Cookies. The bootstrap dependency started prefixing their modules with "uib", which accounts for a significant portion of the changes. Angular changed their cookie api to use "getters" and "puts" instead of accessing the variables directly.

### CODE REVIEW

**Comment by Bradmoon** [comment]
team is building new features on the new angular version.

**Comment by mdskd** [comment]
@rob-miller-777 please resolve merge conflicts.

@amitmawkin @tabladrum any thoughts on this request? gets Hygieia to the latest 1.5.* stable release of angular.

**Comment by tabladrum** [comment]
Yes. We are on board. Taking longer to get to review and test due to holidays.

**Comment by mdskd** [comment]
Figured as much, thanks @tabladrum ! happy holidays!

**Comment by mrpudn** [comment]
LGTM

**Comment by amitmawkin** [comment]
@rob-miller-777 this PR broke our Travis build

```
17:17:46.088 [main] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy() on bean with name 'mongoDbFactory'
17:17:46.088 [main] DEBUG o.s.b.f.s.DisposableBeanAdapter - Invoking destroy method 'close' on bean with name 'mongo'
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.669 sec - in com.capitalone.dashboard.repository.ScopeOwnerRepositoryTest
Running com.capitalone.dashboard.MarkdownTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.004 sec - in com.capitalone.dashboard.MarkdownTest
Running com.capitalone.dashboard.util.EncryptionTests
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.172 sec <<< FAILURE! - in com.capitalone.dashboard.util.EncryptionTests
testDecryptionWithBadKey(com.capitalone.dashboard.util.EncryptionTests)  Time elapsed: 0.014 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: com.capitalone.dashboard.util.EncryptionException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running com.capitalone.dashboard.util.GitBranchSpecTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in com.capitalone.dashboard.util.GitBranchSpecTest
Running com.capitalone.dashboard.model.DashboardTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.capitalone.dashboard.model.DashboardTest```

**Comment by mdskd** [comment]
@amitmawkin taking a look.

**Comment by mdskd** [comment]
@amitmawkin would you be able to manually trigger another build? i can't replicate the failure and it is occurring in a module that wasn't altered as part of this pull request.

i seem to recall seeing an issue with this test in another pull request previously?

**Comment by amitmawkin** [comment]
@mdskd  let me trigger one

**Comment by mdskd** [comment]
thanks @amitmawkin, looks good. i am pretty certain i've seen that test fail before, perhaps it warrants an issue to see if anything can be done to address the flakiness?

**Comment by amitmawkin** [comment]
LGTM

**Comment by satishc1** [comment]
@rob-miller-777 @mdskd @Bradmoon After merging this, I am seeing on my local machine that the searchable dropdown boxes are not working. For example, the build widget dropdown with a large dataset doesn't work. But it works when I revert this PR locally. Are you seeing the same behavior ?

**Comment by mdskd** [comment]
@satishc1 we will investigate this today/tomorrow.

**Comment by satishc1** [comment]
@mdskd Thanks Matt.  As an fyi, I also tried locally building the code with PR 1049 on top off the latest master (which has PR 1027). But the effect was the same... the build widget with a large dataset was unresponsive.

**Comment by mdskd** [comment]
still investigating @satishc1

**Comment by satishc1** [comment]
@mdskd Thanks Matt. If you are able to recreate the issue and feel it will take long to resolve this, please let me know and we can revert the PR. Thanks for your help on this.

**Comment by mdskd** [comment]
@satishc1 definitely experiencing the same

on master with ~10,000 jenkins jobs, the ui-select basically crashes the browser. reverting the merge, with the same list of jenkins jobs, the ui-select responds (albeit slowly)

finding root cause is going to be a bit time-consuming. let's revert for now and we'll dig into the issue. our additional 2 PRs that are closely related (pagination on the API and client) resolve the performance concerns, but as we discuss it more it feels as tho it is just masking the underlying problem.

sincere apologies for the inconvenience

**Comment by mdskd** [comment]
this appear to be a related [issue](https://github.com/angular-ui/ui-select/issues/88)

**Comment by satishc1** [comment]
@mdskd Not a problem. Thank you for researching it. Will revert the PR for now.

**Comment by mdskd** [comment]
we should have some direction on how we intend to address this early next week. i'd like to discuss it with our team before making a decision. folks should all be back on Tuesday.

thanks!

**Comment by mdskd** [comment]
it looks like we are going to combine this PR with the client-side pagination PR we've also got queued up. paging alleviates the performance concerns, additionally a different directive is utilized in that pull request.

we'll get this opened as soon as we can this week.

_note_: it is dependent upon this [PR](https://github.com/capitalone/Hygieia/pull/1049)

thanks!

**Comment by satishc1** [comment]
@mdskd @nireeshT Thanks Matt. We'll take a look at https://github.com/capitalone/Hygieia/pull/1049

**Pull request merged**
