### PR TITLE
Gitlab Custom Protocol/Port

### LINKED ISSUE #957: GitLab Collector is not running
Hi , 

Whenever i run gitlab collector , i get following error .
```
2016-11-17 16:15:38,434 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=10.14.34.73:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 10]}, minWireVersion=0, maxWireVersion=4, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=912360}
2016-11-17 16:15:39,316 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2016-11-17 16:15:39,327 INFO  com.capitalone.dashboard.Application - Started Application in 9.02 seconds (JVM running for 11.151)
2016-11-17 16:18:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Gitlab
2016-11-17 16:18:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-17 16:18:00,010 INFO  c.c.d.collector.CollectorTask - Starting...
2016-11-17 16:18:00,010 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2016-11-17 16:18:00,118 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient.normalizeUrl(DefaultGitlabGitClient.java:239) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.DefaultGitlabGitClient.getCommits(DefaultGitlabGitClient.java:68) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collecteur.GitlabGitCollectorTask.collect(GitlabGitCollectorTask.java:76) ~[gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

Below is my property file 
```properties
dbname=db
dbusername=db
dbpassword=dbpass
dbhost=10.14.34.73
dbport=27017
dbreplicaset=false
dbhostport=10.14.34.73:27017
gitlab.cron=0 0/3 * * * *
gitlab.branche=master
gitlab.apiToken=BrXVX-EFBtkq3Jkv6
gitlab.saveLog=true
gitlab.server=http://10.14.34.73:8181
```

### LINKED ISSUE #973: Gitlab collector failed
```
2016-11-23 12:44:53,550 WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gitlabGitCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946) [spring-boot-1.2.5.RELEASE.jar!/:1.2.5.RELEASE]
        at com.capitalone.dashboard.Application.main(Application.java:16) [gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [gitlab-git-collector-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.NullPointerException: null
        at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:265) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:95) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:82) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:44) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at com.capitalone.dashboard.collector.CollectorTask.onStartup(CollectorTask.java:73) ~[core-2.0.4-SNAPSHOT.jar!/:2.0.4-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 22 common frames omitted
2016-11-23 12:44:53,560 INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'
2016-11-23 12:44:53,565 INFO  o.s.b.l.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/core-2.0.4-SNAPSHOT.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-test-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-data-mongodb-1.8.0.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-expression-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-data-commons-1.11.0.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/slf4j-api-1.7.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/jcl-over-slf4j-1.7.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-jpa-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-core-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/guava-18.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/jsr305-1.3.9.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/mysema-commons-lang-0.2.4.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/bridge-method-annotation-1.13.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-apt-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-codegen-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/codegen-0.6.5.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/ecj-4.3.1.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/javax.inject-1.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/querydsl-mongodb-3.6.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/hibernate-validator-5.1.3.Final.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/jboss-logging-3.1.3.GA.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/classmate-1.0.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/javax.el-api-2.2.4.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/commons-beanutils-1.9.2.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/commons-collections-3.2.1.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-starter-data-mongodb-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-starter-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-autoconfigure-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-boot-starter-logging-1.2.5.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/jul-to-slf4j-1.7.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/log4j-over-slf4j-1.7.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/logback-classic-1.1.3.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/logback-core-1.1.3.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/snakeyaml-1.14.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/mongo-java-driver-3.0.2.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-core-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-tx-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/junit-4.12.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/hamcrest-core-1.3.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-web-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-aop-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/aopalliance-1.0.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-beans-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/spring-context-4.1.7.RELEASE.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/json-simple-1.1.1.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/commons-lang3-3.3.2.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/commons-codec-1.9.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/httpclient-4.3.6.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/httpcore-4.3.3.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/joda-time-2.7.jar!/, jar:file:/home/ubuntu/Hygieia/collectors/scm/gitlab/target/gitlab-git-collector-2.0.4-SNAPSHOT.jar!/lib/joda-convert-1.8.1.jar!/]
2016-11-23 12:44:53,568 INFO  o.s.b.a.l.AutoConfigurationReportLoggingInitializer -

Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)


2016-11-23 12:44:53,569 ERROR o.s.boot.SpringApplication - Application startup failed
```

### PR DESCRIPTION
**Pull request by rob-miller-777**
These changes allow users to choose which protocol and port to use when querying Gitlab's API.  Also added some more information in the Readme about running the collector and which properties are required.

Resolves #957

### CODE REVIEW

**Comment by amitmawkin** [comment]
LGTM

**Comment by vetrivelan25** [comment]
Hi , 
       We need to download latest package again or just add the lines as you mentioned in the above 3 files..
	added support for custon protocol and port
        updated readme
        small readme fix

**Comment by rob-miller-777** [comment]
@vetrivelan25 When this pull request is accepted, you will just need to pull the latest changes from master.

**Comment by tabladrum** [comment]
LGTM.

**Comment by satishc1** [comment]
LGTM

**Comment by tabladrum** [comment]
LGTM

**Comment by vetrivelan25** [comment]
Thanks for your help now it's working!!!

**Comment by rob-miller-777** [comment]
Glad to hear it, let me know if you run into anything else.

**Pull request merged**
