### PR TITLE
Update UI protractor tests README

### PR DESCRIPTION
**Pull request by jozzhart**
I'm trying to get the protractor tests to run.  I'm not even sure if they are meant to be run against the mocked UI, as they are failing.  But I wanted to clarify this first before looking into getting the tests to pass.

### CODE REVIEW

**Comment by nireeshT** [comment]
@jozzhart protractor tests are meant to run against UI and if they are failed, we need to look into more in detail. Can you explain what is intent of this PR.

**Comment by dhirajverma** [comment]
Not related

**Comment by jozzhart** [comment]
@nireeshT Pull request is to update the README to explain process of running tests against the mocked version of the UI (gulp serve --local true).

**Comment by nireeshT** [comment]
@jozzhart  Please update branch.

**Pull request merged**
