### PR TITLE
changed "database" to "dbname" in github docker builder and application.properties example in the readme

### PR DESCRIPTION
**Pull request by 415DomSmith**
Got stuck in trying to get the github collector running. Fix was changing my application.properties file to identify database name as "dbname=", instead of "database=". 

I edited the readme and the docker builder for github to reflect dbname.

### CODE REVIEW

**Comment by tabladrum** [comment]
@415DomSmith - did you submit the CLA?

**Comment by jdamick** [comment]
@tabladrum did he sign?

**Comment by tabladrum** [comment]
@415DomSmith Please fill in the CLA. Thanks

**Comment by 415DomSmith** [comment]
Hey guys,

Sorry for the delay. I have to wait on legal to review the CLA... #enterpriselife

**Comment by tabladrum** [comment]
@415DomSmith - I know what that means :8ball:

**Comment by 415DomSmith** [comment]
I'm closing this out... I don't know why it takes us so long to approve anything, but I'm still waiting.  Sorry @tabladrum

**Pull request closed without merging**
