### PR TITLE
Fix for feature widget not correctly handling some sprint type use cases - #678

### PR DESCRIPTION
**Pull request by MarkRx**
Fix for #678. Backwards compatible. Adds the ability to configure a widget to interpret sprints as either kanban, scrum, or both. This is necessary since it is not possible to deduce which sprint type a project uses from the rest api. I also did some code cleanup while there. The basic issue with the current code is that it interpreted features without sprints as being KANBAN which is not true in all use cases.

Here is how it works:
In order to be considered part of the sprint the feature must not be deleted and must have an "active" sprint asset state if the sprint is set. The following logic also applies:

A feature is part of a scrum sprint if any of the following are true:
- the feature has a sprint set that has start <= now <= end and end < EOT (9999-12-31T59:59:59.999999)

A feature is part of a kanban sprint if any of the following are true:
- the feature does not have a sprint set
- the feature has a sprint set that does not have an end date
- the feature has a sprint set that has an end date >= EOT (9999-12-31T59:59:59.999999)

Note the above are mutually exclusive.

Observe how this handles all of the following use cases:
- Typical scrums (a sprint is live for X number of weeks)
- Kanban without any sprints assigned
- Kanban using a sprint without an end date
- Kanban that was set from previous code that interpretted not having a sprint set as being KANBAN (since we use EOT in the queries above)
- Scrum & Kanban (don't see how this is a real world use case but it works similar to the previous code. Kanban will interpret backlog items as being part of kanban but that issue is existing and cannot be resolved due to lack of information)
- The code in the versionone widget that interprets sprints that have an end date > some cutoff as being KANBAN. This works as it will not end up setting the sprint data which causes the feature to be interpreted as kanban

@amp5208 @tabladrum

### CODE REVIEW

**Comment by MarkRx** [comment]
rebased

**Comment by tabladrum** [comment]
@MarkRx not sure how this conflict came in. Can you please check?

**Comment by MarkRx** [comment]
rebased to keep history clean

**Comment by tabladrum** [comment]
LGTM

**Comment by satishc1** [comment]
LGTM

**Comment by amitmawkin** [comment]
LGTM

**Pull request merged**
