### PR TITLE
Artifactory Collector Phase II - Allow for custom artifact formats

### PR DESCRIPTION
**Pull request by MarkRx**
Changes:

- Allow for configurable custom artifact formats using regex
- Adds modules, classifiers, and extensions to BinaryArtifacts to make them maven and ivy compliant.
- Artifacts published by jenkins no longer include the file extension as part of the artifact name. Instead the value is stored in the artifactExtension field.

Default artifact formats in documentation:
```
# Matches maven artifacts of the form [org]/[module]/[version]/[module]-[version]([-classifier])(.[ext])
artifactory.patterns[0]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<artifact>\\k<module>)-\\k<version>(-(?<classifier>[^\\.]+))?(\\.(?<ext>.+))?
# Matches ivy files of the form [org]/[module]/[revision]/ivy-[revision](-[classifier]).xml 
artifactory.patterns[1]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<artifact>ivy)-\\k<version>(-(?<classifier>[^\\.]+))?\\.(?<ext>xml)
# Matches ivy artifact files of the form [org]/[module]/[revision]/[type]/[artifact]-[revision](-[classifier])(.[ext])
artifactory.patterns[2]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<type>[^/]+)/(?<artifact>[^\\.-/]+)-\\k<version>(-(?<classifier>[^\\.]+))?(\\.(?<ext>.+))?
```

Notes:

- Jenkins collector does not support maven classifiers at this time

### CODE REVIEW

**Comment by MarkRx** [comment]
rebased on to master 2.0.5

**Comment by tabladrum** [comment]
@MarkRx any backward compatibility issue here?

**Comment by MarkRx** [comment]
For the collector just configuration changes.

For existing data it should be handled by my changes in EnvironmentComponentEventListener.java.

**Comment by tabladrum** [comment]
LGTM.

**Comment by tabladrum** [comment]
@MarkRx I had to manually resolve conflicts for hygieia-jenkins-plugin/src/main/java/hygieia/builder/DeployBuilder.java and hygieia-jenkins-plugin/src/main/java/hygieia/builder/ArtifactBuilder.java.

In case you want to review.

**Comment by MarkRx** [comment]
looks fine

**Pull request merged**
