### PR TITLE
Fix Docker build process, score-properties-builder.sh was not valid, hygeia-jenkins-plugin failed due to mismatched dependency

### PR DESCRIPTION
**Pull request by mikesalvia**
Fixes made in order to make `mvn docker:build` finish properly.

### CODE REVIEW

**Comment by jozzhart** [comment]
This resolved the build issue for me.

**Comment by mrlov** [comment]
Please finish this pull request.

Actually `mvn docker:build` is not working correctly...

**Comment by mikesalvia** [comment]
@mrlov WIll finish it now need to re-base.

**Comment by mikesalvia** [comment]
@matthewbeasley Re-based it is re-building then should be good for merge!

**Comment by matthewbeasley** [comment]
@mikesalvia - thanks a lot bud!

**Pull request merged**
