### PR TITLE
changed from maven to gradle

### PR DESCRIPTION
**Pull request by jdamick**
along with embedded mongo to enable testing
added sample properties file for clarity
updated README, for "hudson" as it is now looking for "Jenkins" properties

TODO: normalize names of directories to match and avoid confusion

### CODE REVIEW

**Comment by amitmawkin** [comment]
oh.. I think i fixed the BuildCollector properties issue when it was looking for Jenkins with jenkins and updated the readme.md. I will merge this changes later today, thanks for the gradle build file.

**Comment by jdamick** [comment]
yes.. i'll rebase to those changes..

**Comment by jdamick** [comment]
rebased, please review and merge

**Comment by jdamick** [comment]
@amitmawkin

**Comment by jdamick** [comment]
closing this to pull from the new branch.

**Pull request closed without merging**
