### PR TITLE
Rally

### PR DESCRIPTION
**Pull request by harish233**
Test

### CODE REVIEW

**Comment by tabladrum** [comment]
@harish233 can you resolve the conflict in pom.xml?

**Comment by elangesk** [comment]
@tabladrum
   You mean latest updates contains working stage of Rally collector with hygieia? please suggest...

**Comment by tabladrum** [comment]
@elangesk the main pom.xml in this PR is old. That is the only conflict.

**Comment by elangesk** [comment]
@tabladrum 
   Thanks for your prompt reply. Any idea that rally collector can able to use running stage.

**Comment by timgifford** [comment]
Please close/ignore/delete this PR. I authored this code to experiment and somebody else submitted the PR (I didn't even know this was possible). I'll be deleting my fork this weekend to avoid further confusion.

**Comment by tabladrum** [comment]
Per the original author, I am closing this PR.

**Pull request closed without merging**
