### PR TITLE
Gitlab enhancements

### PR DESCRIPTION
**Pull request by rob-miller-777**
**Bug Fixes:**

- Removed unused code/commented code
- Now filter by collector id when retrieving collectors
- Actually use branch provided by user
- Removed unused application settings 
- Set number of changes on a commit to 1 instead of 159753
- Utilized rest operations class instead of building an Http request 

**Enhancements:**

- Not utilizes Gitlab host set in application properties
- Extracted Url Building logic into a utility class
- Extracted building of Commit object from json string into a mapper class
- Limit number of commits returned to last 14 days
- Utilized clean method from github collector instead of just wiping everything out each time
- Get commits for branch instead of all
- Can now choose branch from UI instead of props file
- Utilize Spring URI Builder to manage url building instead of string manipulation
- Added support for Gitlab's pagination
- Moved API token into the header instead of the Url
- Added ability to provide API Token for private repos
- Added Unit Tests
- Added optional settings for trusting self signed certificates

### CODE REVIEW

**Comment by mdskd** [comment]
greatly improves performance, allows gitlab to work on private instances as well as public

should close out #910 as well

**Comment by amitmawkin** [comment]
@rob-miller-777 please rebase.

**Comment by amitmawkin** [comment]
LGTM

**Comment by satishc1** [comment]
LGTM

**Pull request merged**
