### PR TITLE
Updated documentation on how to setup Hygieia through Docker containers

### PR DESCRIPTION
**Pull request by joshku**
Added step-by-step documentation on how to get Hygieia running through the use of docker containers.

### CODE REVIEW

**Comment by joshku** [comment]
@jdamick @tabladrum @amitmawkin any chance this pull request can be reviewed and merged anytime soon?

**Comment by jdamick** [comment]
we are moving to use capitalone namespace in dockerhub, so i'm holding on this for a moment.. 

@amitmawkin ETA on correct namespace?

**Comment by jimzucker** [comment]
This conflicts with changes I have made to move everything to containers, I will review it and update the docs.

**Comment by jimzucker** [comment]
I think this can be closed now,see #169.

**Comment by jimzucker** [comment]
I think this can be closed with pull request #321

**Comment by jimzucker** [comment]
@tabladrum I think this can be closed based on the merge of my changes. (FYI I will review after all my pulls are merged to ensure docs are correct/up to date.)

**Pull request closed without merging**
