### PR TITLE
Fix log output bug - possible missing spaces between tokens

### PR DESCRIPTION
**Pull request by LiranV**
Hi,
While trying to run the Jenkins build collector I've found that a place without proper spacing in the logs.

Example:
`2016-09-03 04:22:00,302 INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://10.100.68.2380s`

Note that the '0s' is not separated from the host at the end.
My change should make it so that there is always at least one space between the tokens.

### CODE REVIEW

**Comment by tabladrum** [comment]
@LiranV - Thanks for the PR. Did you submit the CLA?

**Comment by LiranV** [comment]
@tabladrum - just submitted the CLA. Thanks.

**Comment by tabladrum** [comment]
LGTM

**Comment by amitmawkin** [comment]
LGTM

**Pull request merged**
