### PR TITLE
Add paging to Jenkins collector

### PR DESCRIPTION
**Pull request by MarkRx**
- Adds paging to the jenkins collector. Page size defaults to 1000. Paging is necessary when there are a very large number of jobs as jenkins seems to choke if a rest response is too large.

@pxk5958

### CODE REVIEW

**Comment by MarkRx** [comment]
rebased

**Comment by tabladrum** [comment]
LGTM

**Comment by tabladrum** [comment]
@nireeshT @satishc1 next up for testing.

**Comment by MarkRx** [comment]
rebased

**Comment by amitmawkin** [comment]
LGTM

**Comment by MarkRx** [comment]
rebased on to 2.0.5

**Comment by mrpudn** [comment]
LGTM

**Comment by tabladrum** [comment]
LGTM

**Pull request merged**
