### PR TITLE
Fixed Feature Widget $query Issues, with tests

### PR DESCRIPTION
**Pull request by amp5208**
I have beefed up integration/unit testing for the feature widget APIs and the repository Core artifacts used by both API and collectors, proving the issue, and thus proving the fix.  I have also ensured that this runs on my machine with the issue resolved with $query.

<strong>Note</strong>:  We are still pending functional testing, because we have to stand-up a new CloudFormation to do it - <em><strong>do not</strong></em> fully merge this pull request until after automated functional testing passes.

### CODE REVIEW

**Comment by amp5208** [comment]
<strong>Note</strong>:  We are still fixing some minor bugs related to functional testing outcomes - I will post a comment here when we are ready for this pull to be reviewed/accepted.

**Comment by amp5208** [comment]
I have fixed most of the syntax and code quality issues you described, with the restriction mentioned in my previous comment.  I have also added the ability for users to specify their Jira instance's custom IssueType value, as this was also noted as a complaint/issue when using the collector for Jira at the following issues:  https://github.com/capitalone/Hygieia/issues/225 ; https://github.com/capitalone/Hygieia/issues/224

**Comment by amp5208** [comment]
Please note, as well.  I am still following up on some minor findings from our internal functional testing; please wait until notified to merge this pull request to master.

**Comment by amp5208** [comment]
@tabladrum and @jdamick  , Please provide any final feedback on this issue, as it is likely going to pass all of testing this morning.  If they are mostly syntax/code quality changes, I can make them before we merge this to master.

**Comment by amp5208** [comment]
This has passed testing fully.  Please merge to master ASAP.

**Comment by amitmawkin** [comment]
merged successfully

**Pull request merged**
