### PR TITLE
add in optional filters into describe instances for aws cloud collector + region support

### PR DESCRIPTION
**Pull request by stevegal**
it may be that you do not want to look at all instances in an account,
but a smaller more focussed list. To do this you can now use filtering on
the aws side to describe only the instances that match your filter.

### CODE REVIEW

**Comment by stevegal** [comment]
Also fixes test location so it is picked up by maven

**Comment by nireeshT** [comment]
@stevegal  Please submit documentation for aws properties file change and possible values. 

https://github.com/capitalone/Hygieia/blob/gh-pages/pages/hygieia/collectors/cloud/aws.md

**Comment by stevegal** [comment]
Will do. I’ll sort that out tomorrow. Thanks.

**Comment by stevegal** [comment]
added see https://github.com/capitalone/Hygieia/pull/2269

**Comment by nireeshT** [comment]
@stevegal  is this change backward compatible

**Comment by stevegal** [comment]
@nireeshT should be from a code perspective as the filters are optional, and, if not provided, you’ll end up with the current functionality. I’ll double check though and get back to you.

**Comment by stevegal** [comment]
@nireeshT confirmed that its all backwardly compatible.

**Comment by stevegal** [comment]
@nireeshT I've also taken the opportunity to add support for non-default regions. This again is optional and will work without setting the property just as before.

**Pull request merged**
