### PR TITLE
Hygieia 2 product health pipeline and related functionality

### LINKED ISSUE #113: UI hard coded to assume API is localhost
UI should have a configuration ability to allow you to point it to a URL for the API
localhost references definitely need to get removed.

```bash
find . -type f |xargs grep /api
./app/dashboard/core/data-factories/build-data.js:        var buildDetailRoute = '/api/build/';
./app/dashboard/core/data-factories/code-analysis-data.js:        var caDetailRoute = '/api/quality/';
./app/dashboard/core/data-factories/code-repo-data.js:        var caDetailRoute = '/api/commit';
./app/dashboard/core/data-factories/collector-data.js:        var itemRoute = '/api/collector/item';
./app/dashboard/core/data-factories/collector-data.js:        var itemsByTypeRoute = '/api/collector/item/type/';
./app/dashboard/core/data-factories/collector-data.js:        var collectorsByTypeRoute = '/api/collector/type/';
./app/dashboard/core/data-factories/dashboard-data.js:        var dashboardRoute = '/api/dashboard';
./app/dashboard/core/data-factories/dashboard-data.js:        var mydashboardRoute = "/api/dashboard/mydashboard";
./app/dashboard/core/data-factories/dashboard-data.js:        var myownerRoute = "/api/dashboard/myowner";
./app/dashboard/core/data-factories/deploy-data.js:        var deployDetailRoute = '/api/deploy/status/';
./app/dashboard/core/data-factories/feature-data.js:		var testTotal = 'http://localhost:8080/api/feature/estimates/total/Team:9933916?component=552e7b21c44a49be6261d54a';
./app/dashboard/core/data-factories/feature-data.js:		var buildTotal = '/api/feature/estimates/total/';
./app/dashboard/core/data-factories/feature-data.js:		var testWip = 'http://localhost:8080/api/feature/estimates/wip/Team:9933916?component=552e7b21c44a49be6261d54a';
./app/dashboard/core/data-factories/feature-data.js:		var buildWip = '/api/feature/estimates/wip/';
./app/dashboard/core/data-factories/feature-data.js:		var testDone = 'http://localhost:8080/api/feature/estimates/done/Team:9933916?component=552e7b21c44a49be6261d54a';
./app/dashboard/core/data-factories/feature-data.js:		var buildDone = '/api/feature/estimates/done/';
./app/dashboard/core/data-factories/feature-data.js:		var testFeatureWip = 'http://localhost:8080/api/feature/estimates/super/Team:9933916?component=552e7b21c44a49be6261d54a';
./app/dashboard/core/data-factories/feature-data.js:		var buildFeatureWip = '/api/feature/estimates/super/';
./app/dashboard/core/data-factories/feature-data.js:		var testSprint = 'http://localhost:8080/api/iteration/Team:9933916?component=552e7b21c44a49be6261d54a';
./app/dashboard/core/data-factories/feature-data.js:		var buildSprint = '/api/iteration/';
./app/dashboard/core/data-factories/feature-data.js:		var testTeams = 'http://localhost:8080/api/collector/item/type/ScopeOwner';
./app/dashboard/core/data-factories/feature-data.js:		var buildTeams = '/api/collector/item/type/ScopeOwner';
./app/dashboard/core/data-factories/feature-data.js:		var testTeamByCollectorItemId = 'http://localhost:8080/api/collector/item/552ecefac44af4d37f321a6e';
./app/dashboard/core/data-factories/feature-data.js:		var buildTeamByCollectorItemId = '/api/collector/item/';
./app/dashboard/core/data-factories/login-data.js:        var LoginDetailRoute = '/api/authenticateUser/';
./app/dashboard/core/data-factories/monitor-data.js:        var monitorRoute = '/api/dashboard/';
./app/dashboard/core/data-factories/monitor-data.js:        var serviceRoute = '/api/service/';
./app/dashboard/core/data-factories/signup-data.js:        var SignupDetailRoute = '/api/registerUser/';
./app/dashboard/core/data-factories/test-suite-data.js:        var caDetailRoute = '/api/test/';
./test-data/commit_detail.json:            "scmCommitLog": "Add /api/canadianflag url to entitlements exclusion list - since its invoked from footer present on /cvv page. ",
```

### LINKED ISSUE #170: commits detail UI showing all 14 days
When you click on a point it should just show that 1 day, not all 14 days.

### LINKED ISSUE #265: modified:   UI/src/index.html
Every time I build it shows up as modified, the build needs to be fixed or the file removed from the tree.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   UI/src/index.html

### LINKED ISSUE #275: Code widget sometimes shows the graph incorrectly
Need to reproduce it. I think for 1 single commit the graph is reversed,...

### PR DESCRIPTION
**Pull request by jayhogan**
This pull request is the culmination of a 4 week development effort to build a product dashboard to display pipeline health across multiple teams. While this is the major feature delivered by this PR, there are also numerous enhancements and bug fixes, including:

## Enhancements

- Ability to create a product dashboard
- Enhance list view to improve filtering and make product dashboards visually distinct
- Ability to add/remove a team to a product dashboard
- Ability reorder the team rows in a product dashboard via drag and drop
- Ability to view pipeline health (i.e Quality) summary metrics for each team on the product dashboard
- Ability to view commit details for a given pipeline stage
- Ability to view quality details for a given team row
- New API to allow pushing of commits to Hygieia via GitHub webhooks
- New API to allow pushing of build data
- New API to allow pushing of binary artifacts
- New API to allow pushing of deploy data
- New API to allow pushing of quality data
- New API to allow pushing of test result data
- Introduction of a client-side database (Dexie) to reduce the amount data transferred from server to client on every request

## Bug fixes

- Fixes #265 by simplifying and improving the UI gulp build process
- Fixes #113 by creating a global config object in the UI to allow command line args to bypass defaults
- Fixes #275 by upgrading to the latest version of the Chartist library and fixing the existing charts accordingly
- Fixes #170 and #274 via creation of new Chartist plugin

hygieia2

### CODE REVIEW

**Comment by softwareklinic** [comment]
Any
Step by step to implement 2.0

**Comment by tabladrum** [comment]
Yes. Coming up.

**Comment by kv113813** [comment]
I am queries to know in the "Product" or "Program" Level Dashboard pipeline health..."size of green and red block are small and big some time- does it symbolize some thing"? Please some explain @tabladrum @jimzucker @jayhogan

**Comment by amitmawkin** [comment]
it symbolizes number of commits, sorry the screen shot is missing the colored legend on the top right hand side

**Comment by kv113813** [comment]
Hi Amit,

Thanks for quick reply....
Please refer the image..I would like to request you if you can little more
elaborate on this. What message it is giving to user when changing to
small- big block with different colors.

**Comment by kv113813** [comment]
How do you read the blocks...vertically with 1000 commits blocks or sequentially. The stack is bit confused.

**Comment by kv113813** [comment]
SO, for 100 commit block what's the time span
How you determine from which day to which day for each block

**Pull request merged**
