### PR TITLE
Feature widget -uib-typehead - Added Any in dropdown options 

### PR DESCRIPTION
**Pull request by nireeshT**
Feature widget -uib-typehead - Added 'Any' in dropdown options

### CODE REVIEW

**Comment by satishc1** [comment]
@nireeshT @tabladrum LGTM

**Comment by sachingupta771** [comment]
Hi All
I'm facing same problem. pls tell any solution that worked for any of you guys.

**Comment by nireeshT** [comment]
@sachingupta771  - start typing "Any" in team text field, it should display in dropdown

**Comment by sachingupta771** [comment]
I have tried all the above steps , pls tell if some other solution is there or not

**Comment by tabladrum** [comment]
@nireeshT

**Comment by nireeshT** [comment]
@sachingupta771 - please share jira collector log.

**Pull request merged**
