### PR TITLE
minimum changes to allow project to build

### PR DESCRIPTION
**Pull request by stevegal**
add in jenkins plugin to main project. Inline getChangeSets as it's not allowed by the annotation.

### CODE REVIEW

**Comment by stevegal** [comment]
your travis build is running out of resources. locally builds fine. Either (1) ignore the jenkins plugin from the main pom or (2) increase the resources on travis

**Comment by stevegal** [comment]
```mvn clean install -q ``` did the trick

**Comment by tabladrum** [comment]
LGTM

**Comment by satishc1** [comment]
@tabladrum LGTM

**Comment by satishc1** [comment]
@stevegal Thanks for the contribution 👍

**Pull request merged**
