### PR TITLE
Fix for issue https://github.com/capitalone/Hygieia/issues/369

### PR DESCRIPTION
**Pull request by RichSteele**
Fix simply does a null check for the user info before using it.

### CODE REVIEW

**Comment by tabladrum** [comment]
@RichSteele Did you submit the CLA? Thanks

**Comment by RichSteele** [comment]
Sorry, missed that.  I'll get the process going and will submit once the
review has been done.

**Comment by jdamick** [comment]
agreed

**Comment by tabladrum** [comment]
@RichSteele Once you have the CLA, we will merge it immediately. Thanks.

**Comment by RichSteele** [comment]
Yes.  Sorry, it's in the hands of legal right now which might take until
3/18 to complete...

**Comment by RichSteele** [comment]
Submitted.  (Finally!)

**Comment by tabladrum** [comment]
:100:

**Pull request merged**
