### PR TITLE
VersionOne Collector Refactor & HTTP Auth Exception Handle

### PR DESCRIPTION
**Pull request by amp5208**
I am merging my content with your working branch for the VersionOne feature collector refactor. I have also added my HTTP auth exception handling, now using the HygieiaException class implementation (added a custom code for HTTP Auth failures that do not throw HTTP auth codes, as is the case with VersionOne). Please review, give feedback, and accept. I have already performed a pull from upstream master to ensure an easy merge.

This is related to the following closed pull request: #419

Repull of the following PR:  https://github.com/capitalone/Hygieia/pull/430

### CODE REVIEW

**Comment by jdamick** [comment]
it looks like this needs to be rebased

**Comment by tabladrum** [comment]
@amp5208 Lets catch up next week to rebase.

**Comment by amp5208** [comment]
This was rebased - it now needs to be re-rebased because of time delay to accept a pull.  I will perform the rebase shortly.

**Comment by amp5208** [comment]
just rebased with both master and the v1c-refactor branches.  please validate and accept the pull.

**Pull request closed without merging**
