### PR TITLE
BugFix- for packaging every file under Ui -dist folder

### LINKED ISSUE #1050: UI dist folder is not packaged correctly by the build scripts
UI dist folder is not getting packaged correctly, currently on expanding the .tar.gz the contents have shell folder and directories and their underlying files are not packaged correctly.

### PR DESCRIPTION
**Pull request by amitmawkin**
This PR Fixes #1050

### CODE REVIEW

**Comment by tabladrum** [comment]
LGTM

**Comment by tabladrum** [comment]
@satishc1 merge this?

**Comment by nireeshT** [comment]
@amitmawkin 
1. During mvn package install, the UI\src\components\themes is not getting added to the dist folder.  Does this folder need to get added to dist during mvn package install ?
2. The tar.gz file which results during assembly looks correct. It copies everything from dist and creates the tar.gz file.

**Comment by amitmawkin** [comment]
@nireeshT only dist contents needs to be packaged and distributed

**Comment by satishc1** [comment]
LGTM

**Comment by nireeshT** [comment]
@amitmawkin  - LGTM

**Pull request merged**
