### PR TITLE
Set DB properties to the correct defaults in all collectors

### PR DESCRIPTION
**Pull request by spennec**
Some collectors have the correct values but most don't. I took the values from the DB setup script and modified all the properties-builder.sh to use them, so we don't have to provide those in the docker-compose.override.yml for each of the collectors.

### CODE REVIEW

**Comment by spennec** [comment]
oops sure, will do. Sorry for the mess.

**Comment by spennec** [comment]
It's all good now, there's no modifications on the score docker file in this PR.

**Comment by Sbrenthughes** [comment]
@spennec Can you update your branch and re push.

**Comment by spennec** [comment]
@Sbrenthughes updated it directly via GitHub, seems ok.

**Pull request merged**
