### PR TITLE
Updated the pom to 2.0.5-SNAPSHOT and cut a release

### PR DESCRIPTION
**Pull request by amitmawkin**
https://github.com/capitalone/Hygieia/releases/tag/Hygieia-2.0.4

### CODE REVIEW

**Comment by MarkRx** [comment]
Does the jenkins plugin version need to correspond to the Hygieia version or is that on its own lifecycle?

**Comment by amitmawkin** [comment]
@MarkRx we made a decision a while back to make all version of each component same for ease of support . 
@tabladrum Do you think we should separate the Jenkins plugin and manage it separately

**Comment by tabladrum** [comment]
At this point, we are ready to make them all even and make Jenkins plugin part of the main project and publish to maven central.

**Comment by satishc1** [comment]
LGTM

**Comment by tabladrum** [comment]
LGTM

**Pull request merged**
