### PR TITLE
Bitbucket Server Implementation & Fixes

### PR DESCRIPTION
**Pull request by MarkRx**
Implements proper collector for Bitbucket Server. Fixes issues #609 and #583.

For reference - there are two "Bitbucket" apis:

- Bitbucket Cloud: https://confluence.atlassian.com/bitbucket/commits-or-commit-resource-389775478.html#commitsorcommitResource-GETacommitslistforarepositoryorcomparecommitsacrossbranches
- Bitbucket Server (used to be called Stash): https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html#idp1513136

Atlassian rebranded Bitbucket to Bitbucket Cloud and Stash to Bitbucket Server. More information here: https://confluence.atlassian.com/bitbucketserver/bitbucket-rebrand-faq-779298912.html

This change allows the configuration to determine which one to use and fixes the bitbucket server (stash) implementation.

Summary of changes:
- Rename to bitbucket collector to align with Atlassian naming scheme
- Added documentation about the difference between Bitbucket Cloud and BitBucket Server (formerly known as Stash)
- Fix/implement Bitbucket Server implementation
- Add ability to specify which product to use via git.product in the config
- Added basic unit tests for BitBucket Server

Changes should still work with older versions of Stash so long as the use the REST api mentioned above.

### CODE REVIEW

**Comment by tabladrum** [comment]
Build breaking due to https://github.com/miickel/gulp-angular-templatecache/issues/124. Latest PR https://github.com/capitalone/Hygieia/pull/633 will fix this.

**Comment by MarkRx** [comment]
How do I kick off another build?

Also, did someone do a force push or history change on the master branch? My bitbucket branch was based off a master branch from Friday but it now has commits that are no longer on the captialone master branch. That seems to be why 7c36a4e and 0c03980 are showing up in this PR.

**Comment by tabladrum** [comment]
there were some bug introduced in NPM. Had to change a dependency version for that. Kicking off the build just now.

**Comment by tabladrum** [comment]
@MarkRx we had some accidental info leak in one PR. Had to clean up some things. Would you mind doing a fresh PR? Let me know.

**Comment by MarkRx** [comment]
I modified my histories to remove the merge commit and thus removed the missing changesets. Since I didn't conflict with anyone and worked in a new folder it should merge fine even though my branch is now based off of an older master.

**Comment by kdatta10** [comment]
1. ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://<stashIP>/rest/api/1.0/projects/stash/repos/projects/<PROJ>/repos/<REPO>/....

when my application.properties has git.host=http://<stash_ip>/stash
git.api=/rest/api/1.0
git.product=server

2. ERROR c.c.d.c.DefaultBitbucketServerClient - Failed to obtain commits from http://<stashIP>/stash/rest/api/1.0/projects/stash/repos/projects/<PROJ>/repos/<REPO>/....

when my application.properties has git.host=http://<stash_ip>/
git.api=/stash/rest/api/1.0
git.product=server


Even I tried with git.product=cloud also. but every time it is taking wrong URL!! it is unnecessarily adding an extra line "projects/stash/repos" after correct URL.

**Pull request merged**
