### PR TITLE
Remove the default values for SONAR_USERNAME and SONAR_PASSWORD.

### LINKED ISSUE #647: Basic auth for sonarqube collector breaks unauthenticated behavior for sonarqube
On initial setup of the sonarqube collector, I received 401 errors every time the collector ran. My docker-compose.override.yml did not contain either `SONAR_USERNAME` or `SONAR_PASSWORD`. When I looked at the logs, those fields were defaulting to `sonarusername` and `sonarpassword`. After declaring `SONAR_USERNAME` and `SONAR_PASSWORD` as empty strings in my override file, they were still being overridden with the default value.

On closer inspection, the `sonar-codequality-collector/docker/sonar-codequality-properties-builder.sh` file sets `SONAR_USERNAME` to "sonarusername" using parameter substitution:

```
#Sonar Authentication Username - default is blank
sonar.username=${SONAR_USERNAME:-sonarusername}
```

There are two issues here. First of all, the default is clearly not blank - if `SONAR_USERNAME` is not provided, it will be set to "sonarusername". Second, this is using the wrong form of parameter substitution. `${FOO:-bar}` sets $FOO to "bar" if $FOO is undefined OR if $FOO is defined but null. This makes it impossible to set the username or password to an empty string.

As a result, there is no way to force an unauthenticated connection when using docker-compose, since the properties-builder file will always overwrite an empty value. The expected behavior should be to use the user-provided username/password without a default value. This way the username and password will only be set if provided by the user explicitly.

### PR DESCRIPTION
**Pull request by cbrenton**
Resolves #647.

### CODE REVIEW

**Comment by jdamick** [comment]
agreed, can you please fill out the CLA

**Comment by tabladrum** [comment]
@cbrenton not sure if you are still around...

**Comment by cbrenton** [comment]
@jdamick @tabladrum sorry, just filled it out.

**Comment by mrpudn** [comment]
@cbrenton can you just resolve the branch conflicts :)

**Comment by cbrenton** [comment]
@mrpudn I'm trying to, and they're resolved on my end, but I'm still seeing a conflict message here. Not sure what I'm doing wrong

**Comment by mrpudn** [comment]
hmm, yeah it's still way behind the upstream repo's master branch.

What steps did you follow?

Usually what I do is have my `origin` remote point to my fork and my `upstream` remote point to the upstream capitalone/Hygieia repo, and then:
```git bash
git checkout master
git pull upstream master
git checkout <my-branch>
git rebase master
git push origin <my-branch>
```

**Comment by cbrenton** [comment]
Ah, that's the problem. I was rebasing to my fork, not the upstream.

**Comment by mrpudn** [comment]
@cbrenton can you make sure that the changes are what you intended - looks like a lot of unrelated changes

**Comment by cbrenton** [comment]
@mrpudn fixed, thanks for the heads up

**Comment by tabladrum** [comment]
LGTM

**Pull request merged**
