### PR TITLE
Fongo repository tests

### PR DESCRIPTION
**Pull request by mdskd**
The existing repository tests in the core module utilize the [flapdoodle](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo) mongo plugin to download and run a mongodb instance when the repository unit tests are executed. To prevent a workstation from connecting to the Internet to download and "install" software, these tests have been refactored to utilize [fongo](https://github.com/fakemongo/fongo).

Fongo is an in-memory implementation of mongodb, it intercepts calls to the mongodb drivers. It is pulled down as a maven dependency, thus no runtime downloading/installation of packages.

The intention of the repository tests feels the same with this change.

Thanks!

### CODE REVIEW

**Comment by Bradmoon** [comment]
this one eliminates the dependency on a physical database for the test and eliminates the need to navigate a proxy for those unfortunate souls that have to function behind one.  feels like good change. do others have comment on change?

cla was submitted on monday.   any idea on eta for cla?

**Comment by tabladrum** [comment]
Should be reviewed this week

**Comment by Bradmoon** [comment]
+1

**Comment by tabladrum** [comment]
Testing this out today and then merge.

**Comment by satishc1** [comment]
👍  Thanks for the contribution. Could have used this feature a couple of weeks back while playing around with the hygieia repo inside our proxy.

**Comment by satishc1** [comment]
LGTM

**Comment by tabladrum** [comment]
LGTM

**Pull request merged**
