### PR TITLE
Rename BuildCollector to HudsonCollector

### PR DESCRIPTION
**Pull request by msabramo**
because it is specific to Hudson/Jenkins.

Cc: @sudarkoff, @aconrad

### CODE REVIEW

**Comment by jdamick** [comment]
agreed, but we need to choose either hudson or jenkins - since they are both used in multiple places (like the properties file)

**Comment by msabramo** [comment]
Yeah, actually I would prefer Jenkins over Hudson. My plan (which I didn't voice) was to submit this PR to change `BuildCollector` to `HudsonCollector` (a relatively small change) and then after merge, submit another PR to rename `Hudson` to `Jenkins`.

**Comment by msabramo** [comment]
Rebased to fix merge conflict.

**Comment by msabramo** [comment]
Rebased again to fix merge conflict (caused by merge of my own change to `Setup.md`).

**Comment by jdamick** [comment]
i think we should just leap frog and just rename to jenkins rather than hudson then jenkins like walked about on gitter..

**Comment by amitmawkin** [comment]
the collector is now jenkins-build-collector, hence closing this pull request

**Pull request closed without merging**
