### PR TITLE
Hygieia Version will now be shown on the Login Page

### PR DESCRIPTION
**Pull request by amitmawkin**
image

### CODE REVIEW

**Comment by amitmawkin** [comment]
LGTM

**Comment by amitmawkin** [comment]
LGTM

**Comment by amitmawkin** [comment]
LGTM

**Comment by amitmawkin** [comment]
Tips picked from this article https://serradev.wordpress.com/2016/02/02/app-version-number-in-java-code-with-maven-and-spring-boot/

**Comment by tabladrum** [comment]
LGTM

**Pull request merged**
