### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by IonicaBizau**
Fixed grammar, and added/removes some commas. :dizzy:

### CODE REVIEW

**Comment by jdamick** [comment]
we should revert, the grammar is not correct..

**Comment by IonicaBizau** [comment]
@jdamick I will just remove the commas, would be that ok?

**Comment by jdamick** [comment]
sounds good

**Comment by IonicaBizau** [comment]
@jdamick Actually, can you please [leave some inline comments](https://github.com/capitalone/Hygieia/pull/148/files) what should be fixed? So, then I will fix it in another PR. :thought_balloon:

**Pull request merged**
