### PR TITLE
17

### PR DESCRIPTION
**Pull request by jstrachan**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/capitalone/Hygieia/pull/18%23issuecomment-124848250%22%2C%20%22https%3A//github.com/capitalone/Hygieia/pull/18%23issuecomment-125042003%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/capitalone/Hygieia/pull/18%23issuecomment-124848250%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thanks%20I%20will%20look%20into%20this%20on%20Monday%2C%20just%20returning%20from%20oscon%2C%20appreciate%20you%20contributing%20to%20Hygieia.%22%2C%20%22created_at%22%3A%20%222015-07-25T13%3A46%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6624821%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/amitmawkin%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20you%20please%20break%20up%20this%20pull%20a%20bit%3F%20%20I%27m%20going%20to%20change%20over%20the%20project%20to%20use%20gradle%20so%20can%20you%20separate%20out%20the%20maven%20changes%20from%20the%20npe%2C%20etc.%20then%20we%20can%20pull%20those%20in%20and%20please%20squash%20the%20commits.%20%20Also%20I%20see%20overlap%20with%20pull%2015%3F%5Cr%5Cn%5Cr%5Cnthanks%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-07-26T21%3A29%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12317%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jdamick%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/capitalone/Hygieia/pull/18#issuecomment-124848250'>General Comment</a></b>
- <a href='https://github.com/amitmawkin'></a> Thanks I will look into this on Monday, just returning from oscon, appreciate you contributing to Hygieia.
- <a href='https://github.com/jdamick'></a> Can you please break up this pull a bit?  I'm going to change over the project to use gradle so can you separate out the maven changes from the npe, etc. then we can pull those in and please squash the commits.  Also I see overlap with pull 15?
thanks

<a href='https://www.codereviewhub.com/capitalone/Hygieia/pull/18?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/capitalone/Hygieia/pull/18?approve=1'></a>&nbsp;<a href='https://github.com/capitalone/Hygieia/pull/18'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by amitmawkin** [comment]
Thanks I will look into this on Monday, just returning from oscon, appreciate you contributing to Hygieia.

**Comment by jdamick** [comment]
Can you please break up this pull a bit?  I'm going to change over the project to use gradle but so can you separate out the maven changes from the npe, etc.  and please squash the commits.  Also I see overlap with pull 15?

thanks

**Comment by jdamick** [comment]
The alternative is for me to cherry pick some of these changes, what would you prefer?

**Comment by msabramo** [comment]
has conflicts

**Comment by amitmawkin** [comment]
all the requested changes have gone in different pulls, hence closing this pull request without merging

**Pull request closed without merging**
