### PR TITLE
JFrog Artifactory Artifact Collector

### PR DESCRIPTION
**Pull request by MarkRx**
Pulls maven and ivy artifacts from JFrog artifactory. Can handle multiple artifactory instances At present assumes the following artifact patterns:

> - 1. Maven artifacts:
> -      [org]/[module]/[version]/[module]-[version][-classifier].[ext]
> - 2. Ivy artifacts:
> -      (a) [org]/[module]/[revision]/[type]/[artifact]-[revision](-[classifier]).[ext]
> -      (b) [org]/[module]/[revision]/ivy-[revision](-[classifier]).xml

Known Issues:
- Cannot pull in updates on artifacts when only properties are updated. This is due to a limitation on the JFrog artifactory rest API.

@pxk5958

### CODE REVIEW

**Comment by amitmawkin** [comment]
@MarkRx is this just a collector or you have a new UI widget to support artifactory widget in works,

**Comment by pxk5958** [comment]
@amitmawkin It's just a collector for now. We configure the artifactory url and the repository to collect from in the configuration file.

**Comment by satishc1** [comment]
@MarkRx @pxk5958 Thanks for the contribution.

**Comment by satishc1** [comment]
LGTM

**Comment by MarkRx** [comment]
Phase II (not started) will be to be able to configure the collector for non-standard formats.

**Comment by tabladrum** [comment]
LGTM

**Pull request merged**
