### PR TITLE
Template removal

### PR DESCRIPTION
**Pull request by brennanananan**
Review https://github.com/capitalone/Hygieia/issues/1116 for initial thoughts regarding this PR.
***Commits have been squashed for convenience.***

* The create dashboard modal has been expanded to allow selection of widgets from all 3 panes (1 below). 
* Update modal has been added to reselect which widgets the owner/admin wants to display (2 below).
* Configure icon has been added next to pane button set to allow for updates. This window can be expanded later to support extra dashboard specific configurations (3 below).
* Update is only available to owner/admin.
* Preexisting dashboards start with all widgets selected to support backwards compatibility, extraneous widgets can be removed by owner/admin.
* If no widgets are selected to be shown for a given pane, a helpful message appears explaining to any users wondering why no widgets are displayed.
* Template variable has been **removed** from the dashboard object, dashboard now maintains a map of available widget types and the panes where those widgets will be found.
* All template views have been consolidated into one single 'team.html/js' view. 

**Note** This PR allows users to select which widgets are displayed, it does not allow for multiple widgets of the same type. IE, having 2 Repository widgets is not supported.

**Example Screens**

1
screen shot 2017-02-02 at 1 16 11 pm

2
screen shot 2017-02-02 at 1 17 31 pm

3
screen shot 2017-02-02 at 1 22 40 pm

### CODE REVIEW

**Comment by mdskd** [comment]
@satishc1 is it appropriate to have closed #415? I think this may be a step towards enabling #415, but I do not believe the capability adding (for instance) multiple branches to the repo widget is supported here.

**Comment by mdskd** [comment]
Please correct me if I misinterpreted the intent of #415 (sorry on mobile, can't edit previous comment)

**Comment by satishc1** [comment]
@mdskd  Good point. I'll reopen https://github.com/capitalone/Hygieia/issues/415

**Comment by satishc1** [comment]
@brennanananan Please rebase.

**Comment by brennanananan** [comment]
Done

**Comment by brennanananan** [comment]
@tabladrum @satishc1 Is there any feedback for this PR? Thanks

**Comment by satishc1** [comment]
@brennanananan @tabladrum This PR is next on our list after we merge the JWT PR. That one is taking a little time sorry. Will get to this one soon.

**Comment by brennanananan** [comment]
@satishc1 No problem! Thanks for the heads up!

**Comment by tinabear** [comment]
Possible to support multiple widgets of the same type? We'd like to show commits info for several git repos on the dashboard.

**Comment by mdskd** [comment]
@tinabear please see comments further up thread. this does not address duplicate widgets, issue #415 is open to discuss said topic. 

thanks!!

**Comment by brennanananan** [comment]
@tabladrum @satishc1 I noticed some chat on the gitter.im around having dynamic layouts as a future feature. Would it be worth closing this PR until the idea for that is a little more developed?

**Comment by brennanananan** [comment]
Closing this PR. There has been talk around customizable templates, if need be this can be reopened if an interest arises in the future.

**Comment by brennanananan** [comment]
@tabladrum @nireeshT Reopening as per discussion in conference call.

**Comment by satishc1** [comment]
@brennanananan @rob-miller-777 Based on your work on this PR, @nireeshT has created a customizable template in https://github.com/capitalone/Hygieia/pull/1581 . Since pr-1581 is a superset of this PR. Please take a look at that one and close this one if you agree. Thanks.

**Comment by satishc1** [comment]
@brennanananan @rob-miller-777 @MarkRx After you've had a chance to review @nireeshT 's latest updates for https://github.com/capitalone/Hygieia/pull/1581 , if u agree, please close this PR and I'll merge https://github.com/capitalone/Hygieia/pull/1581. Thank you.

**Comment by brennanananan** [comment]
Closing in favor of #1581

**Pull request closed without merging**
