### PR TITLE
Reference #323 - Upgraded to java 1.8

### PR DESCRIPTION
**Pull request by jimzucker**

### CODE REVIEW

**Comment by amp5208** [comment]
@jimzucker , Thank you for the contribution.  Please ensure that this change works with the Feature APIs and collectors before merging - we had issues in the past that were caused by a Java version change and is worth validating.

**Comment by jimzucker** [comment]
I am able to test

Github
Both jenkins
Sonar
Hipchat

Is that enough? (I tested yesterday but will redo it on a clean vm)



Sent from my iPhone

On Feb 10, 2016, at 06:54, Arnold Pelka <notifications@github.com<mailto:notifications@github.com>> wrote:


@jimzucker<https://github.com/jimzucker> , Thank you for the contribution. Please ensure that this change works with the Feature APIs and collectors before merging - we had issues in the past that were caused by a Java version change and is worth validating.

-

**Comment by amp5208** [comment]
Normally, yes.  However, to be safe, I will pull your fork and evaluate connectivity with a real Jira / VersionOne instance.  I will post with confirmation of operability.

**Comment by jimzucker** [comment]
@amp5208 thanks.  I created a clean VM and re-ran everything OK:
1 - github
2 - jenkins-build 
3 - jenkins-cucumber
4 - sonar
5 - hip chat

Here is the output:

screenshot 2016-02-10 09 45 55

**Comment by amp5208** [comment]
@jimzucker , I have also built your fork and manually checked the Feature content functionality - your changes did not seem to negatively impact the content.  @jdamick / @tabladrum :  This pull request will not break any recently-merged Feature widget content.

**Comment by jimzucker** [comment]
@amp5208 I see the merge request for the Hymenia-2 if you merge that first I will rebase and reset my changes for Java 1.8..

**Comment by jimzucker** [comment]
@tabladrum I rebased the branch and I put a fix in for a build failure related to bower.

**Comment by jimzucker** [comment]
Rebasing to upstream/master

**Comment by tabladrum** [comment]
Too Big! Is there a way to push only the 1.8 change?

**Comment by jimzucker** [comment]
I am not sure why GIT it showing 290 commits on github I diffed it to upstream/master and I only see a small set of changes…

git diff upstream/master..origin/java18


**I will create a new branch give me a few minutes…




On Feb 16, 2016, at 7:53 AM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Too Big! Is there a way to push only the 1.8 change?

**Comment by jimzucker** [comment]
I am creating java18v2 to make the pull cleaner.

**Comment by jimzucker** [comment]
OK, I created
#332


On Feb 16, 2016, at 7:53 AM, tabladrum <notifications@github.com<mailto:notifications@github.com>> wrote:


Too Big! Is there a way to push only the 1.8 change?

**Pull request closed without merging**
