### PR TITLE
Update package.json, adding missing dependencies.

### PR DESCRIPTION
**Pull request by oshingc**
It's necessary to have the added dependencies at the package.json.
When you try to run UI project these are always required but are not saved in the list.
Hope this update can be accepted.
Note: This solves the issue #590 

Ale
From Peru

### CODE REVIEW

**Comment by jdamick** [comment]
thanks did you sign the CLA?

https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform

**Comment by oshingc** [comment]
Oh no yet, let me see. :D

2016-05-26 11:59 GMT-05:00 jdamick <notifications@github.com>:

> thanks did you sign the CLA?
>
>
> https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/capitalone/Hygieia/pull/595#issuecomment-221931158>
>



-- 
*María Alejandra Gómez Casani*
*Las cosas no se dicen, se hacen porque al hacerlas se dicen solas.*

**Comment by oshingc** [comment]
I signed the CLA.

**Comment by oshingc** [comment]
What about this?

**Comment by tabladrum** [comment]
@jdamick please see. Thanks

**Comment by tabladrum** [comment]
@jdamick Can you merge this?

**Pull request closed without merging**
