### PR TITLE
Signed-off-by: Preacher <gamer4life.insti@gmail.com>

### PR DESCRIPTION
**Pull request by instigardo**
Configured Hygieia-UI for Cloud Foundry.
--Himanshu Saxena (Instigardo)

### CODE REVIEW

**Comment by tabladrum** [comment]
Thanks for the PR. 
Seems like a lot of files have changed! Is it due to reformatting on your IDE? 
Can you describe the new feature and it will be awesome if you can share some screen shots.

**Comment by instigardo** [comment]
Sure, ya its mostly due to IDE.
I am integrating api with UI on CF as soon as its done, I ll do that.

**Comment by tabladrum** [comment]
Can you please do the PR only for the files that you are changing? very hard to review this PR.

**Comment by instigardo** [comment]
ok sure..

**Pull request closed without merging**
