### PR TITLE
Spring Cloud Config

### PR DESCRIPTION
**Pull request by rob-miller-777**
Added a dependency to the "core" project for spring cloud config, and made the properties builder optional by adding a skip flag.  Adding the Spring Cloud Config dependency will make all the dependent boot apps check for a cloud config server on startup.  By default it will check for a config server at "http://localhost:8888".  That can be overridden by setting the `
spring.cloud.config.uri` property.

### CODE REVIEW

**Comment by rob-miller-777** [comment]
Any updates here?

**Comment by rob-miller-777** [comment]
@satishc1 Have you guys had a chance to take a look at this one?  We are hoping this one get's accepted soon so we don't have to make this change manually to our internal codebase.

**Comment by satishc1** [comment]
@rob-miller-777 Looking at this one today. Thanks.

**Comment by satishc1** [comment]
@rob-miller-777 @tabladrum 
Couple of questions on spring cloud config.

Are you planning to store your properties files in github?
Are you ok with storing passwords in properties files? Is jasypt encryption going to be used to encrypt it? Where would you store the key for the encryption ?

**Comment by rob-miller-777** [comment]
We are going to store our properties files in our own internally hosted git repo.  As far as storing passwords, spring cloud config supports encryption/decryption, thought I haven't had time to play around with that yet.  Here is some documentation on that if you wanted to take a look.  https://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_encryption_and_decryption

**Comment by satishc1** [comment]
@rob-miller-777 @tabladrum LGTM.

**Pull request merged**
