### PR TITLE
Reference #305 - Added container for Sonar

### PR DESCRIPTION
**Pull request by jimzucker**
screenshot 2016-02-01 18 40 57
Reference #306 - Updated version of jacoco to make it compatible with Sonar
Reference #305 - Added container for Sonar

### CODE REVIEW

**Comment by jimzucker** [comment]
I rebased to master to remove the conflicts.

**Comment by jdamick** [comment]
you need to rebase this

**Comment by jimzucker** [comment]
I rebased earlier today, can you check the commit I did about 2 hours ago?

**Comment by jimzucker** [comment]
Odd, not sure what did wrong, I just re-did it and diffed it to upstream/master, let me know what you think after it rebuilds.

**Comment by jimzucker** [comment]
I see the problem if you look at commit :
| *   b497082 - Merge remote-tracking branch 'upstream/master' (6 days ago) amp5208

screenshot 2016-02-07 09 18 09


It does not appear to have been rebased correctly and it deleted previous changes:
screenshot 2016-02-07 09 17 25

**Comment by jimzucker** [comment]
I am going to close this pull request as the master has lost some changes. I will consolidate and test everything in one branch.

**Pull request closed without merging**
